/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file snetAasIpvx.c
*
* @brief This is a external API definition for IPVX unit (part of egress processing)
*
* @version   1
********************************************************************************
*/
#include <asicSimulation/SKernel/smain/smain.h>
#include <asicSimulation/SKernel/smem/smemCheetah.h>
#include <asicSimulation/SKernel/smem/smemAas.h>
#include <asicSimulation/SKernel/suserframes/snet.h>
#include <asicSimulation/SKernel/skernel.h>
#include <asicSimulation/SKernel/cheetahCommon/sregCheetah.h>
#include <asicSimulation/SKernel/cheetahCommon/sregBobcat2.h>
#include <asicSimulation/SKernel/cheetahCommon/sregFalcon.h>
#include <asicSimulation/SKernel/suserframes/snetCheetahEgress.h>
#include <asicSimulation/SKernel/suserframes/snetCheetah2TStart.h>
#include <asicSimulation/SKernel/suserframes/snetCheetah3.h>
#include <asicSimulation/SKernel/suserframes/snetXCat.h>
#include <asicSimulation/SKernel/suserframes/snetCheetah3CentralizedCnt.h>
#include <asicSimulation/SKernel/suserframes/snetXCatPolicer.h>
#include <asicSimulation/SKernel/suserframes/snetCheetahEq.h>
#include <asicSimulation/SKernel/suserframes/snetLion.h>
#include <asicSimulation/SKernel/suserframes/snetAasHa.h>
#include <asicSimulation/SKernel/suserframes/snetAasIpvx.h>
#include <asicSimulation/SLog/simLog.h>
#include <asicSimulation/SLog/simLogInfoTypePacket.h>

#define SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_NAME          \
     STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_PACKET_CMD_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_BYPASS_TTL_OPTIONS_OR_HOP_EXTENTION_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_CPU_CODE_INDEX_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_INGRESS_MIRRROR_TO_ANALYZER_INDEX_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_PRECEDE_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_TARGET_EPG_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_NEXT_HOP_VID1_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_MARKING_EN_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_INDEX_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MODIFY_DSCP_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MODIFY_UP_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_NEXT_HOP_EVLAN_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_DIP_ACCESS_LEVEL_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_SIP_ACCESS_LEVEL_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_IPV6_DEST_SITE_ID_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_IPV6_SCOPE_CHECK_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_COUNTER_SET_INDEX_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MTU_INDEX_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_ARP_BC_TRAP_MIRROR_EN_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_APP_SPECIFIC_CPU_CODE_EN_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_SIP_FILTER_EN_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_DEC_TTL_OR_HOP_COUNT_E)\
     ,STR(SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_ICMP_REDIRECT_EXCEP_MIRROR_E)

static char * sip7IpvxL3NheProfileFieldsTableNames[
    SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS___LAST_VALUE___E] =
    {SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_NAME};


static SNET_ENTRY_FORMAT_TABLE_STC sip7IpvxL3NheProfileTableFieldsFormat[
    SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS___LAST_VALUE___E] =
{
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_PACKET_CMD_E */
    STANDARD_FIELD_MAC(3)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_BYPASS_TTL_OPTIONS_OR_HOP_EXTENTION_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_CPU_CODE_INDEX_E */
    ,STANDARD_FIELD_MAC(2)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_INGRESS_MIRRROR_TO_ANALYZER_INDEX_E */
    ,STANDARD_FIELD_MAC(6)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_PRECEDE_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         1,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_INGRESS_MIRRROR_TO_ANALYZER_INDEX_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_TARGET_EPG_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         12,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_INGRESS_MIRRROR_TO_ANALYZER_INDEX_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_NEXT_HOP_VID1_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         12,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_INGRESS_MIRRROR_TO_ANALYZER_INDEX_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_MARKING_EN_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         1,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_PRECEDE_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_INDEX_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         7,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_MARKING_EN_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MODIFY_DSCP_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         2,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_QOS_PROFILE_INDEX_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MODIFY_UP_E */
    ,    {FIELD_SET_IN_RUNTIME_CNS,
         2,
         SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MODIFY_DSCP_E}

    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_NEXT_HOP_EVLAN_E */
    ,EXPLICIT_FIELD_MAC(25,16)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_DIP_ACCESS_LEVEL_E */
    ,STANDARD_FIELD_MAC(6)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_SIP_ACCESS_LEVEL_E */
    ,STANDARD_FIELD_MAC(6)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_IPV6_DEST_SITE_ID_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_IPV6_SCOPE_CHECK_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_COUNTER_SET_INDEX_E */
    ,STANDARD_FIELD_MAC(3)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_MTU_INDEX_E */
    ,STANDARD_FIELD_MAC(3)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_ARP_BC_TRAP_MIRROR_EN_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_APP_SPECIFIC_CPU_CODE_EN_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_SIP_FILTER_EN_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_DEC_TTL_OR_HOP_COUNT_E */
    ,STANDARD_FIELD_MAC(1)
    /* SMEM_SIP7_IPVX_ROUTER_L3NHE_PROFILE_TABLE_FIELDS_ICMP_REDIRECT_EXCEP_MIRROR_E */
    ,STANDARD_FIELD_MAC(1)
};

/**
* @internal snetAasIpvxTablesFormatInit function
* @endinternal
*
* @brief   init the format of IPVX tables.
*
* @param[in] devObjPtr                - pointer to device object.
*/
void snetAasIpvxTablesFormatInit(
    IN SKERNEL_DEVICE_OBJECT            * devObjPtr
)
{
    LION3_TABLES_FORMAT_INIT_MAC(
         devObjPtr, SKERNEL_TABLE_FORMAT_IPVX_ROUTER_L3NHE_PROFILE_E,
         sip7IpvxL3NheProfileTableFieldsFormat, sip7IpvxL3NheProfileFieldsTableNames);
}
