/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file snetAasHa.c
*
* @brief This is a external API definition for HA unit (part of egress processing)
*
* @version   1
********************************************************************************
*/
#include <asicSimulation/SKernel/smain/smain.h>
#include <asicSimulation/SKernel/smem/smemCheetah.h>
#include <asicSimulation/SKernel/smem/smemAas.h>
#include <asicSimulation/SKernel/suserframes/snet.h>
#include <asicSimulation/SKernel/skernel.h>
#include <asicSimulation/SKernel/cheetahCommon/sregCheetah.h>
#include <asicSimulation/SKernel/cheetahCommon/sregBobcat2.h>
#include <asicSimulation/SKernel/cheetahCommon/sregFalcon.h>
#include <asicSimulation/SKernel/suserframes/snetCheetahEgress.h>
#include <asicSimulation/SKernel/suserframes/snetCheetah2TStart.h>
#include <asicSimulation/SKernel/suserframes/snetCheetah3.h>
#include <asicSimulation/SKernel/suserframes/snetXCat.h>
#include <asicSimulation/SKernel/suserframes/snetCheetah3CentralizedCnt.h>
#include <asicSimulation/SKernel/suserframes/snetXCatPolicer.h>
#include <asicSimulation/SKernel/suserframes/snetCheetahEq.h>
#include <asicSimulation/SKernel/suserframes/snetLion.h>
#include <asicSimulation/SKernel/suserframes/snetAasHa.h>
#include <asicSimulation/SLog/simLog.h>
#include <asicSimulation/SLog/simLogInfoTypePacket.h>


#define SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_NAME                    \
     STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TUNNEL_TYPE_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TAG0_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TAG1_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_UP0_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DEI0_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_UP1_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DEI1_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TTL_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_PROTOCOL_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DF_FLAG_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_OFFSET_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_FLAG_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_UDP_SRC_PORT_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_GRE_FLAGS_AND_VER_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DIP_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_SIP_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_ANALYZER_INDEX_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_CNC_PTR_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_ASSIGNMENT_PROFILE_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_BITS_E)\
    ,STR(SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_RESERVED_E)

static char * sip7HaIpv4VportTunnelStartFieldsTableNames[
    SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaIpv4VportTunnelStartTableFieldsFormat[
    SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TUNNEL_TYPE_E*/
     STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TAG0_QOS_MARKING_MODE_E*/
     STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TAG1_QOS_MARKING_MODE_E*/
     STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_UP0_E*/
     STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DEI0_E*/
     STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_UP1_E*/
     STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DEI1_E*/
     STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_TTL_E*/
     STANDARD_FIELD_MAC(8),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_PROTOCOL_E*/
     STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_E*/
     STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_MARKING_MODE_E*/
     STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DF_FLAG_E*/
     STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_OFFSET_E*/
     STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_FLAG_E*/
     STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E*/
     STANDARD_FIELD_MAC(5),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_UDP_SRC_PORT_E*/
        /*Protocol == "UDP"*/
        {FIELD_SET_IN_RUNTIME_CNS,
         16,
         SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E},
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_GRE_FLAGS_AND_VER_E*/
        /*Protocol != "UDP"*/
        {FIELD_SET_IN_RUNTIME_CNS,
         16,
         SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E},

    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_DIP_E*/
     EXPLICIT_FIELD_MAC(60, 32),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_SIP_E*/
     STANDARD_FIELD_MAC(32),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_ANALYZER_INDEX_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_CNC_PTR_E*/
    STANDARD_FIELD_MAC(19),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_ASSIGNMENT_PROFILE_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_BITS_E*/
    STANDARD_FIELD_MAC(32),
    /*SMEM_SIP7_HA_IPV4_VPORT_TUNNEL_START_TABLE_FIELDS_RESERVED_E*/
    STANDARD_FIELD_MAC(13)
};

#define SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_NAME                    \
    STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TUNNEL_TYPE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TAG0_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TAG1_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_UP0_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DEI0_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_UP1_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DEI1_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TTL_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_PROTOCOL_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DF_FLAG_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_OFFSET_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_FLAG_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_UDP_SRC_PORT_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_GRE_FLAGS_AND_VER_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DIP_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_SIP_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_ANALYZER_INDEX_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_CNC_PTR_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_ASSIGNMENT_PROFILE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_BITS_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_ENTROPY_MODE_E)\
    ,STR(SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_VALUE_E)

static char * sip7HaIpv6VportTunnelStartFieldsTableNames[
    SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaIpv6VportTunnelStartTableFieldsFormat[
    SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TUNNEL_TYPE_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TAG0_QOS_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TAG1_QOS_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_UP0_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DEI0_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_UP1_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DEI1_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_TTL_E*/
    STANDARD_FIELD_MAC(8),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_PROTOCOL_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DSCP_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DF_FLAG_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_OFFSET_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_AUTO_TUNNEL_FLAG_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E*/
    STANDARD_FIELD_MAC(5),

     /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_UDP_SRC_PORT_E*/
        /*Protocol == "UDP"*/
        {FIELD_SET_IN_RUNTIME_CNS,
         16,
         SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E},
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_GRE_FLAGS_AND_VER_E*/
        /*Protocol != "UDP"*/
        {FIELD_SET_IN_RUNTIME_CNS,
         16,
         SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_PROFILE_NUMBER_E},

    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_DIP_E*/
     EXPLICIT_FIELD_MAC(60, 128),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_SIP_E*/
     STANDARD_FIELD_MAC(128),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_ANALYZER_INDEX_E*/
     STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_CNC_PTR_E*/
    STANDARD_FIELD_MAC(19),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_ASSIGNMENT_PROFILE_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_BITS_E*/
    STANDARD_FIELD_MAC(32),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_MODE_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_ENTROPY_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_IPV6_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_VALUE_E*/
    STANDARD_FIELD_MAC(16)
};


#define SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_NAME             \
    STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_TUNNEL_TYPE_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_TAG0_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_TAG1_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_UP0_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_DEI0_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_UP1_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_DEI1_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_THREAD_ID_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_ANALYZER_INDEX_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_ROW_LABELS_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_MPLS_ETHERTYPE_SELECT_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_CNC_PTR_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_PROFILE_ID_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_BITS_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_NUMBER_OF_LABELS_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_LAST_QOS_UNIFORM_LABEL_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_QOS_MAPPING_TABLE_INDEX_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_LAST_TTL_UNIFORM_LABEL_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_CW_INDEX_E)\
    ,STR(SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_INSERTION_E)

static char * sip7HaMplsVportTunnelStartFieldsTableNames[
    SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaMplsVportTunnelStartTableFieldsFormat[
    SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_TUNNEL_TYPE_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_TAG0_QOS_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_TAG1_QOS_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_UP0_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_DEI0_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_UP1_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_DEI1_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_THREAD_ID_E*/
    STANDARD_FIELD_MAC(8),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_ANALYZER_INDEX_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_ROW_LABELS_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_MPLS_ETHERTYPE_SELECT_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_CNC_PTR_E*/
    STANDARD_FIELD_MAC(19),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_PROFILE_ID_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_ID_GCF_BITS_E*/
    STANDARD_FIELD_MAC(32),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_NUMBER_OF_LABELS_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_LAST_QOS_UNIFORM_LABEL_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_QOS_MAPPING_TABLE_INDEX_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_LAST_TTL_UNIFORM_LABEL_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_CW_INDEX_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_MPLS_VPORT_TUNNEL_START_TABLE_FIELDS_FLOW_LABEL_INSERTION_E*/
    STANDARD_FIELD_MAC(1)
};


#define SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_NAME \
    STR(SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_MPLS_PW_LABEL_PUSH_ENABLE_E)\
    ,STR(SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_SOURCE_BASED_MPLS_LABEL_E)\
    ,STR(SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_SOURCE_BASED_MPLS_LABEL_EXP_E)\
    ,STR(SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_SOURCE_BASED_MPLS_LABEL_TTL_E)\
    ,STR(SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_ROUTER_MAC_SA_INDEX_E)

static char * sip7HaSrcEport1FieldsTableNames[
    SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaSrcEport1TableFieldsFormat[
    SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS____LAST_VALUE___E] =
{
   /*SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_MPLS_PW_LABEL_PUSH_ENABLE_E*/
    STANDARD_FIELD_MAC(1),
   /*SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_SOURCE_BASED_MPLS_LABEL_E*/
    STANDARD_FIELD_MAC(20),
   /*SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_SOURCE_BASED_MPLS_LABEL_EXP_E*/
    STANDARD_FIELD_MAC(3),
   /*SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_SOURCE_BASED_MPLS_LABEL_TTL_E*/
    STANDARD_FIELD_MAC(8),
   /*SMEM_SIP7_HA_SRC_EPORT_1_TABLE_FIELDS_ROUTER_MAC_SA_INDEX_E*/
    STANDARD_FIELD_MAC(12)
};

#define SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS_NAME \
     STR(SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS_PUSHED_TAG_VLAN_ID_VLAUE_E)\
    ,STR(SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS_FORCE_E_TAG_IE_PID_TO_DEFAULT_E)

static char * sip7HaSrcEport2FieldsTableNames[
    SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaSrcEport2TableFieldsFormat[
    SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS_PUSHED_TAG_VLAN_ID_VLAUE_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_SRC_EPORT_2_TABLE_FIELDS_FORCE_E_TAG_IE_PID_TO_DEFAULT_E*/
    STANDARD_FIELD_MAC(1)
};

#define SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_NAME \
    STR(SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_INVALID_CRC_MODE_E)\
    ,STR(SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_PORT_TIMESTAMP_RECEPTION_EN_E)\
    ,STR(SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_TRUNK_ID_E)\
    ,STR(SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_HSR_BASE_LSDU_OFFSET_E)

static char * sip7HaSrcPhysicalPort2FieldsTableNames[
    SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaSrcPhysicalPort2TableFieldsFormat[
    SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_INVALID_CRC_MODE_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_PORT_TIMESTAMP_RECEPTION_EN_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_TRUNK_ID_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_SRC_PHYSICAL_PORT_2_TABLE_FIELDS_HSR_BASE_LSDU_OFFSET_E*/
    STANDARD_FIELD_MAC(6)
};

#define SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_NAME \
    STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MODE_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_TPID_INDEX_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_TPID_INDEX_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_VLAN_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_VLAN_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_UP_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_DEI_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_UP_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_DEI_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_DSCP_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_QOS_MAPPING_TABLE_INDEX_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_L2_HEADER_UP0_DEI0_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_L2_HEADER_UP1_DEI1_QOS_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_DSCP_MARKING_MODE_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MAC_SA_INDEX_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MESH_ID_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MTU_PROFILE_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_ANALYZER_INDEX_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MAC_DA_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_ASSIGN_MAC_DA_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_CNC_PTR_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_GCF_PROFILE_ID_E)\
    ,STR(SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_FLOW_ID_GCF_BITS_E)

static char * sip7HaTargetCircuitsFieldsTableNames[
    SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaTargetCircuitsTableFieldsFormat[
    SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_TPID_INDEX_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_TPID_INDEX_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_VLAN_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_VLAN_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_UP_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_DEI_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_UP_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_DEI_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_DSCP_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_QOS_MAPPING_TABLE_INDEX_E*/
    STANDARD_FIELD_MAC(7),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_L2_HEADER_UP0_DEI0_QOS_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_L2_HEADER_UP1_DEI1_QOS_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_DSCP_MARKING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MAC_SA_INDEX_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MESH_ID_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MTU_PROFILE_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_ANALYZER_INDEX_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_MAC_DA_E*/
    STANDARD_FIELD_MAC(48),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_ASSIGN_MAC_DA_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_CNC_PTR_E*/
    STANDARD_FIELD_MAC(17),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_GCF_PROFILE_ID_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_TARGET_CIRCUITS_TABLE_FIELDS_FLOW_ID_GCF_BITS_E*/
    STANDARD_FIELD_MAC(40)
};


#define SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_NAME \
     STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_MODE_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_TPID_INDEX_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_TPID_INDEX_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_VLAN_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_VLAN_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_UP_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_DEI_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_UP_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_DEI_E)\
    ,STR(SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_MTU_PROFILE_E)

static char * sip7HaAnalyzersTargetCircuitsFieldsTableNames[
    SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaAnalyzersTargetCircuitsTableFieldsFormat[
    SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_TPID_INDEX_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_TPID_INDEX_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_VLAN_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_VLAN_E*/
    STANDARD_FIELD_MAC(12),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_UP_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG0_DEI_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_UP_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_TAG1_DEI_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_ANALYZERS_TARGET_CIRCUITS_TABLE_FIELDS_MTU_PROFILE_E*/
    STANDARD_FIELD_MAC(4)
};

#define SMEM_SIP7_HA_QUEUE_MAPPING_TABLE_FIELDS_NAME \
    STR(SMEM_SIP7_HA_QUEUE_MAPPING_TABLE_FIELDS_TAIL_DROP_PROFILE_E)

static char * sip7HaQueueMappingFieldsTableNames[
    SMEM_SIP7_HA_QUEUE_MAPPING_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_QUEUE_MAPPING_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaQueueMappingTableFieldsFormat[
    SMEM_SIP7_HA_QUEUE_MAPPING_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_QUEUE_MAPPING_TABLE_FIELDS_TAIL_DROP_PROFILE_E*/
    STANDARD_FIELD_MAC(10)
};

#define SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_NAME \
    STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP0_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI0_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP0_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_DEI0_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP0_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP0_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP1_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI1_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP1_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_DEI1_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP1_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP1_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP2_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI2_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP2_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG2_DEI2_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP2_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP2_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP3_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI3_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP3_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_DEI3_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP3_E)\
    ,STR(SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP3_E)

static char * sip7HaQosMappingFieldsTableNames[
    SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaQosMappingTableFieldsFormat[
    SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP0_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI0_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP0_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_DEI0_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP0_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP0_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP1_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI1_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP1_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_DEI1_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP1_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP1_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP2_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI2_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP2_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG2_DEI2_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP2_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP2_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_UP3_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG0_DEI3_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_UP3_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_TAG1_DEI3_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_DSCP3_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_QOS_MAPPING_TABLE_FIELDS_EXP3_E*/
    STANDARD_FIELD_MAC(3)
};

#define SMEM_SIP7_HA_HEADER_FIELDS_TABLE_FIELDS_NAME \
    STR(SMEM_SIP7_HA_HEADER_FIELDS_ENTRY_TYPE_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_SUB_TYPE_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_ANALYZER_INDEX_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_EGRESS_MIRROR_MODE_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_SUB_THREAD_ID_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_CNC_PTR_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_GCF_PROFILE_ID_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_GCF_BITS_0_4_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_NUMBER_OF_LABELS_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_LAST_QOS_UNIFORM_LABEL_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_GLOBAL_EXP_MAPPING_TBL_INDEX_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_LAST_TTL_UNIFORM_LABEL_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_CW_INDEX_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_FLOW_LABEL_INSERTION_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_GCF_BITS_5_47_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_FLOW_ID_E)\
    ,STR(SMEM_SIP7_HA_HEADER_FIELDS_MPLS_LABELS_E)

static char * sip7HaHeaderFieldsFieldsTableNames[
    SMEM_SIP7_HA_HEADER_FIELDS_TABLE_FIELDS____LAST_VALUE___E] =
    {SMEM_SIP7_HA_HEADER_FIELDS_TABLE_FIELDS_NAME};

static SNET_ENTRY_FORMAT_TABLE_STC sip7HaHeaderFieldsTableFieldsFormat[
    SMEM_SIP7_HA_HEADER_FIELDS_TABLE_FIELDS____LAST_VALUE___E] =
{
    /*SMEM_SIP7_HA_HEADER_FIELDS_ENTRY_TYPE_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_HEADER_FIELDS_SUB_TYPE_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_HEADER_FIELDS_ANALYZER_INDEX_E*/
    STANDARD_FIELD_MAC(6),
    /*SMEM_SIP7_HA_HEADER_FIELDS_EGRESS_MIRROR_MODE_E*/
    STANDARD_FIELD_MAC(2),
    /*SMEM_SIP7_HA_HEADER_FIELDS_SUB_THREAD_ID_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_HEADER_FIELDS_CNC_PTR_E*/
    STANDARD_FIELD_MAC(19),
    /*SMEM_SIP7_HA_HEADER_FIELDS_GCF_PROFILE_ID_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_HEADER_FIELDS_GCF_BITS_0_4_E*/
    STANDARD_FIELD_MAC(5),
    /*SMEM_SIP7_HA_HEADER_FIELDS_NUMBER_OF_LABELS_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_HEADER_FIELDS_LAST_QOS_UNIFORM_LABEL_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_HEADER_FIELDS_GLOBAL_EXP_MAPPING_TBL_INDEX_E*/
    STANDARD_FIELD_MAC(3),
    /*SMEM_SIP7_HA_HEADER_FIELDS_LAST_TTL_UNIFORM_LABEL_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_HEADER_FIELDS_CW_INDEX_E*/
    STANDARD_FIELD_MAC(4),
    /*SMEM_SIP7_HA_HEADER_FIELDS_FLOW_LABEL_INSERTION_E*/
    STANDARD_FIELD_MAC(1),
    /*SMEM_SIP7_HA_HEADER_FIELDS_GCF_BITS_5_47_E*/
    STANDARD_FIELD_MAC(43),
    /*SMEM_SIP7_HA_HEADER_FIELDS_FLOW_ID_E*/
    STANDARD_FIELD_MAC(20),
    /*SMEM_SIP7_HA_HEADER_FIELDS_MPLS_LABELS_E*/
    STANDARD_FIELD_MAC(510)
};

extern char * lion3HaEPort1FieldsTableNames[
    SMEM_LION3_HA_EPORT_TABLE_1_FIELDS____LAST_VALUE___E];
static SNET_ENTRY_FORMAT_TABLE_STC sip7HaEPort1TableFieldsFormat[
    SMEM_LION3_HA_EPORT_TABLE_1_FIELDS____LAST_VALUE___E] =
{
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_VLAN_TRANS_EN                   */
    STANDARD_FIELD_MAC(2),/* was 1 bit in sip5*/
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_EGRESS_TAG0_TPID_INDEX          */
    STANDARD_FIELD_MAC(3),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_EGRESS_TAG1_TPID_INDEX          */
    STANDARD_FIELD_MAC(3),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_HEADER_TPID_INDEX            */
    STANDARD_FIELD_MAC(3),

    /* TunnelType != "MPLS" */

        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_EXT                          */
        {FIELD_SET_IN_RUNTIME_CNS,
         32,
         SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_HEADER_TPID_INDEX},

    /* TunnelType == "MPLS" */

        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_MPLS_PW_LABEL_PUSH_ENABLE       */
        {FIELD_SET_IN_RUNTIME_CNS,
         1,
         SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_HEADER_TPID_INDEX},
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_MPLS_PW_LABEL                   */
        STANDARD_FIELD_MAC(20),
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_MPLS_PW_LABEL_EXP               */
        STANDARD_FIELD_MAC(3),
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_MPLS_PW_LABEL_TTL               */
        STANDARD_FIELD_MAC(8),
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_PUSH_MPLS_FLOW_LABEL_ENABLE     */
        STANDARD_FIELD_MAC(1),
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_FORCE_ARP_TS_EPORT_DECISION     */
        STANDARD_FIELD_MAC(1),
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TUNNEL_START                    */
        STANDARD_FIELD_MAC(1),

    /*TunnelStart = "1"*/
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_POINTER                      */
        {FIELD_SET_IN_RUNTIME_CNS,
         19,/*was 16 in sip5_20*/
         SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TUNNEL_START},

    /*TunnelStart = "0"*/
        /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ARP_POINTER                     */
        {FIELD_SET_IN_RUNTIME_CNS,
         20,/*was 18 in sip5_20*/
         SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TUNNEL_START},

    /*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_PASSENGER_TYPE               */
        {FIELD_SET_IN_RUNTIME_CNS,
         1,
         SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TS_POINTER},

/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_MODIFY_MAC_SA                   */
    {FIELD_SET_IN_RUNTIME_CNS,
     1,
     SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ARP_POINTER},

/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_MODIFY_MAC_DA                   */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TRILL_INTERFACE_ENABLE          */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_KEEP_ORIGINAL_TAG0_TPID         */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_KEEP_ORIGINAL_TAG1_TPID         */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ENABLE_EGRESS_UP_MAPPING        */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ENABLE_EGRESS_DSCP_MAPPING      */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ENABLE_EGRESS_EXP_MAPPING       */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ENABLE_EGRESS_TC_DP_MAPPING     */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_QOS_MAPPING_TABLE_INDEX         */
    STANDARD_FIELD_MAC(4),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_ROUTER_MAC_SA_INDEX             */
    STANDARD_FIELD_MAC(12),/* was 8 in sip5_20 */
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_DP_TO_CFI_MAP_ENABLE             */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_PUSH_SOURCE_BASED_MPLS_LABEL     */
    STANDARD_FIELD_MAC(1),
/*SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_PUSH_EVLAN_BASED_MPLS_LABEL      */
    STANDARD_FIELD_MAC(1),
/*SMEM_SIP6_HA_EPORT_TABLE_1_FIELDS_PHA_THREAD_NUMBER                 */
    STANDARD_FIELD_MAC(8),
/*SMEM_SIP6_10_HA_EPORT_TABLE_1_FIELDS_NESTED_VLAN_EN                 */
    STANDARD_FIELD_MAC(1),
/*SMEM_SIP6_30_HA_EPORT_TABLE_1_FIELDS_NESTED_VLAN_MODE_E */ /*97..98*/
    STANDARD_FIELD_MAC(2),
/*SMEM_SIP6_30_HA_EPORT_TABLE_1_FIELDS_HSR_PRP_LAN_ID_E   */ /*99..102*/
    STANDARD_FIELD_MAC(4),
/*SMEM_SIP6_30_HA_EPORT_TABLE_1_FIELDS_L2NAT_ENABLE_E     */ /*103*/
    STANDARD_FIELD_MAC(1),
    /* SMEM_SIP6_30_HA_EPORT_TABLE_1_FIELDS_NAT_PTR_E */
    {FIELD_SET_IN_RUNTIME_CNS,
     18,/*was 16 in sip5_20*/
     SMEM_LION3_HA_EPORT_TABLE_1_FIELDS_TUNNEL_START}
};

/**
* @internal snetAasHaTablesFormatInit function
* @endinternal
*
* @brief   init the format of HA tables.
*
* @param[in] devObjPtr                - pointer to device object.
*/
void snetAasHaTablesFormatInit(
    IN SKERNEL_DEVICE_OBJECT            * devObjPtr
)
{
    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_IPV4_VPORT_TUNNEL_START_E,
        sip7HaIpv4VportTunnelStartTableFieldsFormat, sip7HaIpv4VportTunnelStartFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_IPV6_VPORT_TUNNEL_START_E,
        sip7HaIpv6VportTunnelStartTableFieldsFormat, sip7HaIpv6VportTunnelStartFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_MPLS_VPORT_TUNNEL_START_E,
        sip7HaMplsVportTunnelStartTableFieldsFormat, sip7HaMplsVportTunnelStartFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_SRC_EPORT_1_E,
        sip7HaSrcEport1TableFieldsFormat, sip7HaSrcEport1FieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_SRC_EPORT_2_E,
        sip7HaSrcEport2TableFieldsFormat, sip7HaSrcEport2FieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_SRC_PHYSICAL_PORT_2_E,
        sip7HaSrcPhysicalPort2TableFieldsFormat, sip7HaSrcPhysicalPort2FieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_TARGET_CIRCUITS_E,
        sip7HaTargetCircuitsTableFieldsFormat, sip7HaTargetCircuitsFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_ANALYZERS_TARGET_CIRCUITS_E,
        sip7HaAnalyzersTargetCircuitsTableFieldsFormat, sip7HaAnalyzersTargetCircuitsFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_QUEUE_MAPPING_E,
        sip7HaQueueMappingTableFieldsFormat, sip7HaQueueMappingFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_QOS_MAPPING_E,
        sip7HaQosMappingTableFieldsFormat, sip7HaQosMappingFieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_EGRESS_EPORT_1_E,
        sip7HaEPort1TableFieldsFormat, lion3HaEPort1FieldsTableNames);

    LION3_TABLES_FORMAT_INIT_MAC(
        devObjPtr, SKERNEL_TABLE_FORMAT_HA_HEADER_FIELDS_E,
        sip7HaHeaderFieldsTableFieldsFormat, sip7HaHeaderFieldsFieldsTableNames);
}
