/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAasMacGlobalExtUnits.h
*
* @brief AAS port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAasMacGlobalExtUnits_H
#define __mvHwsAasMacGlobalExtUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  AAS_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_MAC_RESET__E,
  /*1*/  AAS_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_MAC_CLK_EN_E,
  /*2*/  AAS_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_APP_RESET__E,
  /*3*/  AAS_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_APP_CLK_EN_E,
  /*4*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CLOCK_DIVIDER_CONTROL_CLK_RATIO_E,
  /*5*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CONTROL_APB_WATCHDOG_TIMER_MAX_VAL_E,
  /*6*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CONTROL_MAC_ABU_WATCHDOG_E,
  /*7*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CONTROL_CYC_TO_STRETCH_MAC2APP_E,
  /*8*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CONTROL_CYC_TO_STRETCH_MAC2REG_E,
  /*9*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CONTROL_CYC_TO_STRETCH_APP2REG_E,
  /*10*/  AAS_MAC_GLOBAL_EXT_GLOBAL_CONTROL_XOFF_GEN_ALWAYS_SYNC_E,
  /*11*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_GLOBAL_INTERRUPT_CAUSE_INT_SUM_E,
  /*12*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_E,
  /*13*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_ABU_BAD_ADDRESS_ERROR_E,
  /*14*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_ABU_WATCHDOG_ERROR_E,
  /*15*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_MASK_GLOBAL_INTERRUPT_MASK_E,
  /*16*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_GLOBAL_INTERRUPT_SUMMARY_INT_SUM_E,
  /*17*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_GLOBAL_INT_SUM_E,
  /*18*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P0_INT_SUM_E,
  /*19*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P1_INT_SUM_E,
  /*20*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P2_INT_SUM_E,
  /*21*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P3_INT_SUM_E,
  /*22*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P4_INT_SUM_E,
  /*23*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P5_INT_SUM_E,
  /*24*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P6_INT_SUM_E,
  /*25*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P7_INT_SUM_E,
  /*26*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P8_INT_SUM_E,
  /*27*/  AAS_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_MASK_GLOBAL_INTERRUPT_SUMMARY_MASK_E,
  /*28*/  AAS_MAC_GLOBAL_EXT_LAST_VIOLATION_LAST_VIOLATION_E,
  /*29*/  AAS_MAC_GLOBAL_EXT_GLOBAL_MAC_METAL_FIX_MAC_METAL_FIX_E,
  /*30*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_GLOBAL_L1_INTERRUPT_SUMMARY_INT_SUM_E,
  /*31*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P0_L1_INT_SUM_E,
  /*32*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P1_L1_INT_SUM_E,
  /*33*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P2_L1_INT_SUM_E,
  /*34*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P3_L1_INT_SUM_E,
  /*35*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P4_L1_INT_SUM_E,
  /*36*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P5_L1_INT_SUM_E,
  /*37*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P6_L1_INT_SUM_E,
  /*38*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P7_L1_INT_SUM_E,
  /*39*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_CAUSE_P8_L1_INT_SUM_E,
  /*40*/  AAS_MAC_GLOBAL_EXT_GLOBAL_L1_INTERRUPT_SUMMARY_MASK_GLOBAL_L1_INTERRUPT_SUMMARY_MASK_E,
          AAS_MAC_GLOBAL_EXT_GLOBAL_REGISTER_LAST_E /* should be last */
} MV_HWS_AAS_MAC_GLOBAL_EXT_UNIT_FIELDS_ENT;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsAasMacGlobalExtUnits_H */

