/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAasRsFecUnits.h
*
* @brief AAS port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAasRsFecUnits_H
#define __mvHwsAasRsFecUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_BYPASS_CORRECTION_E,
  /*1*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_BYPASS_ERROR_INDICATION_E,
  /*2*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_DEGRADE_ENABLE_E,
  /*3*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_AM16_COPY_DIS_E,
  /*4*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_KP_ENABLE_E,
  /*5*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_TC_PAD_VALUE_E,
  /*6*/  AAS_RSFEC_UNIT_RSFEC_CONTROL_P0_TC_PAD_ALTER_E,
  /*7*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_BYPASS_CORRECTION_ABILITY_E,
  /*8*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_BYPASS_INDICATION_ABILITY_E,
  /*9*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_HIGH_SER_E,
  /*10*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_DEGRADE_SER_ABILITY_E,
  /*11*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_DEGRADE_SER_E,
  /*12*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_RX_AM_SF2_E,
  /*13*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_RX_AM_SF1_E,
  /*14*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_RX_AM_SF0_E,
  /*15*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_AMPS_LOCK_E,
  /*16*/  AAS_RSFEC_UNIT_RSFEC_STATUS_P0_FEC_ALIGN_STATUS_E,
  /*17*/  AAS_RSFEC_UNIT_RSFEC_CCW_LO_P0_RSFEC_CCW_LO_E,
  /*18*/  AAS_RSFEC_UNIT_RSFEC_CCW_HI_P0_RSFEC_CCW_HI_E,
  /*19*/  AAS_RSFEC_UNIT_RSFEC_NCCW_LO_P0_RSFEC_NCCW_LO_E,
  /*20*/  AAS_RSFEC_UNIT_RSFEC_NCCW_HI_P0_RSFEC_NCCW_HI_E,
  /*21*/  AAS_RSFEC_UNIT_RSFEC_LANE_MAP_P0_RSFEC_LANE_MAP_E,
  /*22*/  AAS_RSFEC_UNIT_RSFEC_DEC_THRESH_P0_RSFEC_DEC_THRESH_E,
  /*23*/  AAS_RSFEC_UNIT_HISER_CW_HISER_CW_E,
  /*24*/  AAS_RSFEC_UNIT_HISER_THRESH_HISER_THRESH_E,
  /*25*/  AAS_RSFEC_UNIT_HISER_TIME_HISER_TIME_E,
  /*26*/  AAS_RSFEC_UNIT_DEGRADE_SET_CW_DEGRADE_SET_CW_E,
  /*27*/  AAS_RSFEC_UNIT_DEGRADE_SET_CW_HI_DEGRADE_SET_CW_HI_E,
  /*28*/  AAS_RSFEC_UNIT_DEGRADE_SET_THRESH_DEGRADE_SET_THRESH_E,
  /*29*/  AAS_RSFEC_UNIT_DEGRADE_SET_THRESH_HI_DEGRADE_SET_THRESH_HI_E,
  /*30*/  AAS_RSFEC_UNIT_DEGRADE_CLEAR_CW_DEGRADE_CLEAR_CW_E,
  /*31*/  AAS_RSFEC_UNIT_DEGRADE_CLEAR_CW_HI_DEGRADE_CLEAR_CW_HI_E,
  /*32*/  AAS_RSFEC_UNIT_DEGRADE_CLEAR_THRESH_DEGRADE_CLEAR_THRESH_E,
  /*33*/  AAS_RSFEC_UNIT_DEGRADE_CLEAR_THRESH_HI_DEGRADE_CLEAR_THRESH_HI_E,
  /*34*/  AAS_RSFEC_UNIT_VENDOR_VL0_0_UM0_E,
  /*35*/  AAS_RSFEC_UNIT_VENDOR_VL0_0_UM1_E,
  /*36*/  AAS_RSFEC_UNIT_VENDOR_VL0_1_UM2_E,
  /*37*/  AAS_RSFEC_UNIT_VENDOR_VL1_0_UM0_E,
  /*38*/  AAS_RSFEC_UNIT_VENDOR_VL1_0_UM1_E,
  /*39*/  AAS_RSFEC_UNIT_VENDOR_VL1_1_UM2_E,
  /*40*/  AAS_RSFEC_UNIT_VENDOR_VL2_0_UM0_E,
  /*41*/  AAS_RSFEC_UNIT_VENDOR_VL2_0_UM1_E,
  /*42*/  AAS_RSFEC_UNIT_VENDOR_VL2_1_UM2_E,
  /*43*/  AAS_RSFEC_UNIT_VENDOR_VL3_0_UM0_E,
  /*44*/  AAS_RSFEC_UNIT_VENDOR_VL3_0_UM1_E,
  /*45*/  AAS_RSFEC_UNIT_VENDOR_VL3_1_UM2_E,
  /*46*/  AAS_RSFEC_UNIT_VENDOR_VL4_0_UM0_E,
  /*47*/  AAS_RSFEC_UNIT_VENDOR_VL4_0_UM1_E,
  /*48*/  AAS_RSFEC_UNIT_VENDOR_VL4_1_UM2_E,
  /*49*/  AAS_RSFEC_UNIT_VENDOR_VL5_0_UM0_E,
  /*50*/  AAS_RSFEC_UNIT_VENDOR_VL5_0_UM1_E,
  /*51*/  AAS_RSFEC_UNIT_VENDOR_VL5_1_UM2_E,
  /*52*/  AAS_RSFEC_UNIT_VENDOR_VL6_0_UM0_E,
  /*53*/  AAS_RSFEC_UNIT_VENDOR_VL6_0_UM1_E,
  /*54*/  AAS_RSFEC_UNIT_VENDOR_VL6_1_UM2_E,
  /*55*/  AAS_RSFEC_UNIT_VENDOR_VL7_0_UM0_E,
  /*56*/  AAS_RSFEC_UNIT_VENDOR_VL7_0_UM1_E,
  /*57*/  AAS_RSFEC_UNIT_VENDOR_VL7_1_UM2_E,
  /*58*/  AAS_RSFEC_UNIT_VENDOR_VL8_0_UM0_E,
  /*59*/  AAS_RSFEC_UNIT_VENDOR_VL8_0_UM1_E,
  /*60*/  AAS_RSFEC_UNIT_VENDOR_VL8_1_UM2_E,
  /*61*/  AAS_RSFEC_UNIT_VENDOR_VL9_0_UM0_E,
  /*62*/  AAS_RSFEC_UNIT_VENDOR_VL9_0_UM1_E,
  /*63*/  AAS_RSFEC_UNIT_VENDOR_VL9_1_UM2_E,
  /*64*/  AAS_RSFEC_UNIT_VENDOR_VL10_0_UM0_E,
  /*65*/  AAS_RSFEC_UNIT_VENDOR_VL10_0_UM1_E,
  /*66*/  AAS_RSFEC_UNIT_VENDOR_VL10_1_UM2_E,
  /*67*/  AAS_RSFEC_UNIT_VENDOR_VL11_0_UM0_E,
  /*68*/  AAS_RSFEC_UNIT_VENDOR_VL11_0_UM1_E,
  /*69*/  AAS_RSFEC_UNIT_VENDOR_VL11_1_UM2_E,
  /*70*/  AAS_RSFEC_UNIT_VENDOR_VL12_0_UM0_E,
  /*71*/  AAS_RSFEC_UNIT_VENDOR_VL12_0_UM1_E,
  /*72*/  AAS_RSFEC_UNIT_VENDOR_VL12_1_UM2_E,
  /*73*/  AAS_RSFEC_UNIT_VENDOR_VL13_0_UM0_E,
  /*74*/  AAS_RSFEC_UNIT_VENDOR_VL13_0_UM1_E,
  /*75*/  AAS_RSFEC_UNIT_VENDOR_VL13_1_UM2_E,
  /*76*/  AAS_RSFEC_UNIT_VENDOR_VL14_0_UM0_E,
  /*77*/  AAS_RSFEC_UNIT_VENDOR_VL14_0_UM1_E,
  /*78*/  AAS_RSFEC_UNIT_VENDOR_VL14_1_UM2_E,
  /*79*/  AAS_RSFEC_UNIT_VENDOR_VL15_0_UM0_E,
  /*80*/  AAS_RSFEC_UNIT_VENDOR_VL15_0_UM1_E,
  /*81*/  AAS_RSFEC_UNIT_VENDOR_VL15_1_UM2_E,
  /*82*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR0_LO_SYMBLERR0_LO_E,
  /*83*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR0_HI_SYMBLERR0_HI_E,
  /*84*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR1_LO_SYMBLERR1_LO_E,
  /*85*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR1_HI_SYMBLERR1_HI_E,
  /*86*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR2_LO_SYMBLERR2_LO_E,
  /*87*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR2_HI_SYMBLERR2_HI_E,
  /*88*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR3_LO_SYMBLERR3_LO_E,
  /*89*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR3_HI_SYMBLERR3_HI_E,
  /*90*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR4_LO_SYMBLERR4_LO_E,
  /*91*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR4_HI_SYMBLERR4_HI_E,
  /*92*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR5_LO_SYMBLERR5_LO_E,
  /*93*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR5_HI_SYMBLERR5_HI_E,
  /*94*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR6_LO_SYMBLERR6_LO_E,
  /*95*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR6_HI_SYMBLERR6_HI_E,
  /*96*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR7_LO_SYMBLERR7_LO_E,
  /*97*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR7_HI_SYMBLERR7_HI_E,
  /*98*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR8_LO_SYMBLERR8_LO_E,
  /*99*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR8_HI_SYMBLERR8_HI_E,
  /*100*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR9_LO_SYMBLERR9_LO_E,
  /*101*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR9_HI_SYMBLERR9_HI_E,
  /*102*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR10_LO_SYMBLERR10_LO_E,
  /*103*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR10_HI_SYMBLERR10_HI_E,
  /*104*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR11_LO_SYMBLERR11_LO_E,
  /*105*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR11_HI_SYMBLERR11_HI_E,
  /*106*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR12_LO_SYMBLERR12_LO_E,
  /*107*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR12_HI_SYMBLERR12_HI_E,
  /*108*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR13_LO_SYMBLERR13_LO_E,
  /*109*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR13_HI_SYMBLERR13_HI_E,
  /*110*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR14_LO_SYMBLERR14_LO_E,
  /*111*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR14_HI_SYMBLERR14_HI_E,
  /*112*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR15_LO_SYMBLERR15_LO_E,
  /*113*/  AAS_RSFEC_UNIT_RSFEC_SYMBLERR15_HI_SYMBLERR15_HI_E,
  /*114*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_AMPS_LOCK_E,
  /*115*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_ALIGN_STATUS_LH_E,
  /*116*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_MARKER_CHECK_RESTART_E,
  /*117*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_ALIGN_STATUS_LL_E,
  /*118*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_INFO2_VENDOR_AMPS_LOCK_LANES_E,
  /*119*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_REVISION_REVISION_E,
  /*120*/  AAS_RSFEC_UNIT_RSFEC_VENDOR_ALIGN_STATUS_RSFEC_VENDOR_ALIGN_STATUS_E,
  /*121*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C0_FEC_HI_BER_THRESHOLD_C0_E,
  /*122*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C1_FEC_HI_BER_THRESHOLD_C1_E,
  /*123*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C2_FEC_HI_BER_THRESHOLD_C2_E,
  /*124*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C3_FEC_HI_BER_THRESHOLD_C3_E,
  /*125*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C4_FEC_HI_BER_THRESHOLD_C4_E,
  /*126*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C5_FEC_HI_BER_THRESHOLD_C5_E,
  /*127*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C6_FEC_HI_BER_THRESHOLD_C6_E,
  /*128*/  AAS_RSFEC_UNIT_FEC_HI_BER_THRESHOLD_C7_FEC_HI_BER_THRESHOLD_C7_E,
           AAS_RSFEC_UNIT_REGISTER_LAST_E /* should be last */
} MV_HWS_AAS_RSFEC_UNIT_FIELDS_ENT;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsAasRsFecUnits_H */

