/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAasMac400Units.h
*
* @brief AAS port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAasMac400Units_H
#define __mvHwsAasMac400Units_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  AAS_MAC400_REVISION_CORE_REVISION_E,
  /*1*/  AAS_MAC400_REVISION_CORE_VERSION_E,
  /*2*/  AAS_MAC400_REVISION_CUSTOMER_REVISION_E,
  /*3*/  AAS_MAC400_SCRATCH_SCRATCH_E,
  /*4*/  AAS_MAC400_COMMAND_CONFIG_TX_ENA_E,
  /*5*/  AAS_MAC400_COMMAND_CONFIG_RX_ENA_E,
  /*6*/  AAS_MAC400_COMMAND_CONFIG_PROMIS_EN_E,
  /*7*/  AAS_MAC400_COMMAND_CONFIG_CRC_FWD_E,
  /*8*/  AAS_MAC400_COMMAND_CONFIG_PAUSE_FWD_E,
  /*9*/  AAS_MAC400_COMMAND_CONFIG_PAUSE_IGNORE_E,
  /*10*/  AAS_MAC400_COMMAND_CONFIG_TX_ADDR_INS_E,
  /*11*/  AAS_MAC400_COMMAND_CONFIG_LOOPBACK_EN_E,
  /*12*/  AAS_MAC400_COMMAND_CONFIG_TX_PAD_EN_E,
  /*13*/  AAS_MAC400_COMMAND_CONFIG_SW_RESET_E,
  /*14*/  AAS_MAC400_COMMAND_CONFIG_CMD_FRAME_ENA_E,
  /*15*/  AAS_MAC400_COMMAND_CONFIG_PHY_TXENA_E,
  /*16*/  AAS_MAC400_COMMAND_CONFIG_SEND_IDLE_E,
  /*17*/  AAS_MAC400_COMMAND_CONFIG_NO_LGTH_CHECK_E,
  /*18*/  AAS_MAC400_COMMAND_CONFIG_PFC_MODE_E,
  /*19*/  AAS_MAC400_COMMAND_CONFIG_PAUSE_PFC_COMP_E,
  /*20*/  AAS_MAC400_COMMAND_CONFIG_RX_SFD_ANY_E,
  /*21*/  AAS_MAC400_COMMAND_CONFIG_TX_FLUSH_E,
  /*22*/  AAS_MAC400_COMMAND_CONFIG_TX_FIFO_RESET_E,
  /*23*/  AAS_MAC400_COMMAND_CONFIG_FLT_HDL_DIS_E,
  /*24*/  AAS_MAC400_COMMAND_CONFIG_SHORT_PREAMBLE_E,
  /*25*/  AAS_MAC400_COMMAND_CONFIG_INV_LOOP_E,
  /*26*/  AAS_MAC400_MAC_ADDR_0_MAC_ADDRESS_0_E,
  /*27*/  AAS_MAC400_MAC_ADDR_1_MAC_ADDRESS_1_E,
  /*28*/  AAS_MAC400_FRM_LENGTH_FRM_LENGTH_E,
  /*29*/  AAS_MAC400_FRM_LENGTH_FRM_LENGTH_TX_MTU_E,
  /*30*/  AAS_MAC400_COMMAND_CONFIG_2_NO_TXFIFO_CLEAR_ON_LINK_FAIL_E,
  /*31*/  AAS_MAC400_COMMAND_CONFIG_2_DATA_FIFO_AF_THRESHOLD_E,
  /*32*/  AAS_MAC400_COMMAND_CONFIG_2_CTRL_FIFO_AF_THRESHOLD_E,
  /*33*/  AAS_MAC400_COMMAND_CONFIG_2_EOP_STATUS_FIFO_AF_THRESHOLD_E,
  /*34*/  AAS_MAC400_RX_FIFO_SECTIONS_RX_SECTION_AVAIL_E,
  /*35*/  AAS_MAC400_RX_FIFO_SECTIONS_RX_SECTION_EMPTY_E,
  /*36*/  AAS_MAC400_TX_FIFO_SECTIONS_TX_SECTION_AVAIL_THRESHOLD_E,
  /*37*/  AAS_MAC400_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_THRESHOLD_E,
  /*38*/  AAS_MAC400_HASHTABLE_LOAD_HASH_TABLE_ADDRESS_E,
  /*39*/  AAS_MAC400_HASHTABLE_LOAD_ENABLE_MULTICAST_FRAME_E,
  /*40*/  AAS_MAC400_STATUS_RX_LOC_FAULT_E,
  /*41*/  AAS_MAC400_STATUS_RX_REM_FAULT_E,
  /*42*/  AAS_MAC400_STATUS_PHY_LOS_E,
  /*43*/  AAS_MAC400_STATUS_TS_AVAIL_E,
  /*44*/  AAS_MAC400_STATUS_TX_EMPTY_E,
  /*45*/  AAS_MAC400_STATUS_RX_EMPTY_E,
  /*46*/  AAS_MAC400_STATUS_TX_ISIDLE_E,
  /*47*/  AAS_MAC400_TX_IPG_LENGTH_TXIPG_E,
  /*48*/  AAS_MAC400_TX_IPG_LENGTH_MAC400_SHORT_IPG_E,
  /*49*/  AAS_MAC400_TX_IPG_LENGTH_TXIPGCOMPENSATION_E,
  /*50*/  AAS_MAC400_CL01_PAUSE_QUANTA_CL0_PAUSE_QUANTA_E,
  /*51*/  AAS_MAC400_CL01_PAUSE_QUANTA_CL1_PAUSE_QUANTA_E,
  /*52*/  AAS_MAC400_CL23_PAUSE_QUANTA_CL2_PAUSE_QUANTA_E,
  /*53*/  AAS_MAC400_CL23_PAUSE_QUANTA_CL3_PAUSE_QUANTA_E,
  /*54*/  AAS_MAC400_CL45_PAUSE_QUANTA_CL4_PAUSE_QUANTA_E,
  /*55*/  AAS_MAC400_CL45_PAUSE_QUANTA_CL5_PAUSE_QUANTA_E,
  /*56*/  AAS_MAC400_CL67_PAUSE_QUANTA_CL6_PAUSE_QUANTA_E,
  /*57*/  AAS_MAC400_CL67_PAUSE_QUANTA_CL7_PAUSE_QUANTA_E,
  /*58*/  AAS_MAC400_CL01_QUANTA_THRESH_CL0_QUANTA_THRESH_E,
  /*59*/  AAS_MAC400_CL01_QUANTA_THRESH_CL1_QUANTA_THRESH_E,
  /*60*/  AAS_MAC400_CL23_QUANTA_THRESH_CL2_QUANTA_THRESH_E,
  /*61*/  AAS_MAC400_CL23_QUANTA_THRESH_CL3_QUANTA_THRESH_E,
  /*62*/  AAS_MAC400_CL45_QUANTA_THRESH_CL4_QUANTA_THRESH_E,
  /*63*/  AAS_MAC400_CL45_QUANTA_THRESH_CL5_QUANTA_THRESH_E,
  /*64*/  AAS_MAC400_CL67_QUANTA_THRESH_CL6_QUANTA_THRESH_E,
  /*65*/  AAS_MAC400_CL67_QUANTA_THRESH_CL7_QUANTA_THRESH_E,
  /*66*/  AAS_MAC400_RX_PAUSE_STATUS_RX_PAUSE_STATUS_E,
  /*67*/  AAS_MAC400_TS_TIMESTAMP_TS_TIMESTAMP_E,
  /*68*/  AAS_MAC400_XIF_MODE_ONE_STEP_ENA_E,
  /*69*/  AAS_MAC400_XIF_MODE_PFC_PULSE_MODE_E,
  /*70*/  AAS_MAC400_XIF_MODE_PFC_LP_MODE_E,
  /*71*/  AAS_MAC400_XIF_MODE_PFC_LP_16PRI_E,
          AAS_MAC400_REGISTER_LAST_E /* should be last */
} MV_HWS_AAS_MAC400_UNIT_FIELDS_ENT;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsAasMac400Units_H */

