/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAasMac100Units.h
*
* @brief AAS port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAasMac100Units_H
#define __mvHwsAasMac100Units_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  AAS_MAC100_REVISION_CORE_REVISION_E,
  /*1*/  AAS_MAC100_REVISION_CORE_VERSION_E,
  /*2*/  AAS_MAC100_REVISION_CUSTOMER_REVISION_E,
  /*3*/  AAS_MAC100_SCRATCH_SCRATCH_E,
  /*4*/  AAS_MAC100_COMMAND_CONFIG_TX_ENA_E,
  /*5*/  AAS_MAC100_COMMAND_CONFIG_RX_ENA_E,
  /*6*/  AAS_MAC100_COMMAND_CONFIG_CRC_FWD_E,
  /*7*/  AAS_MAC100_COMMAND_CONFIG_PAUSE_FWD_E,
  /*8*/  AAS_MAC100_COMMAND_CONFIG_PAUSE_IGNORE_E,
  /*9*/  AAS_MAC100_COMMAND_CONFIG_TX_ADDR_INS_E,
  /*10*/  AAS_MAC100_COMMAND_CONFIG_LOOPBACK_EN_E,
  /*11*/  AAS_MAC100_COMMAND_CONFIG_TX_PAD_EN_E,
  /*12*/  AAS_MAC100_COMMAND_CONFIG_SW_RESET_E,
  /*13*/  AAS_MAC100_COMMAND_CONFIG_CNTL_FRAME_ENA_E,
  /*14*/  AAS_MAC100_COMMAND_CONFIG_PHY_TXENA_E,
  /*15*/  AAS_MAC100_COMMAND_CONFIG_SEND_IDLE_E,
  /*16*/  AAS_MAC100_COMMAND_CONFIG_PMAC_PAUSE_MASK_P_E,
  /*17*/  AAS_MAC100_COMMAND_CONFIG_PMAC_PAUSE_MASK_E_E,
  /*18*/  AAS_MAC100_COMMAND_CONFIG_PFC_MODE_E,
  /*19*/  AAS_MAC100_COMMAND_CONFIG_PAUSE_PFC_COMP_E,
  /*20*/  AAS_MAC100_COMMAND_CONFIG_RX_SFD_ANY_E,
  /*21*/  AAS_MAC100_COMMAND_CONFIG_TX_FLUSH_E,
  /*22*/  AAS_MAC100_COMMAND_CONFIG_TX_LOWP_ENA_E,
  /*23*/  AAS_MAC100_COMMAND_CONFIG_REG_LOWP_RXEMPTY_E,
  /*24*/  AAS_MAC100_COMMAND_CONFIG_FLT_TX_STOP_E,
  /*25*/  AAS_MAC100_COMMAND_CONFIG_TX_FIFO_RESET_E,
  /*26*/  AAS_MAC100_COMMAND_CONFIG_FLT_HDL_DIS_E,
  /*27*/  AAS_MAC100_COMMAND_CONFIG_PMAC_TX_PAUSE_DIS_E,
  /*28*/  AAS_MAC100_COMMAND_CONFIG_PMAC_RX_PAUSE_DIS_E,
  /*29*/  AAS_MAC100_COMMAND_CONFIG_SHORT_PREAMBLE_E,
  /*30*/  AAS_MAC100_COMMAND_CONFIG_NO_PREAMBLE_E,
  /*31*/  AAS_MAC100_PMAC_MAC_ADDR_0_MAC_ADDRESS_0_E,
  /*32*/  AAS_MAC100_PMAC_MAC_ADDR_1_MAC_ADDRESS_1_E,
  /*33*/  AAS_MAC100_PMAC_FRM_LENGTH_FRM_LENGTH_E,
  /*34*/  AAS_MAC100_PMAC_FRM_LENGTH_TX_MTU_E,
  /*35*/  AAS_MAC100_COMMAND_CONFIG_2_NO_TXFIFO_CLEAR_ON_LINK_FAIL_E,
  /*36*/  AAS_MAC100_COMMAND_CONFIG_2_DATA_FIFO_AF_THRESHOLD_E,
  /*37*/  AAS_MAC100_COMMAND_CONFIG_2_CTRL_FIFO_AF_THRESHOLD_E,
  /*38*/  AAS_MAC100_PMAC_RX_FIFO_SECTIONS_RX_SECTION_FULL_E,
  /*39*/  AAS_MAC100_PMAC_RX_FIFO_SECTIONS_RX_SECTION_EMPTY_E,
  /*40*/  AAS_MAC100_PMAC_TX_FIFO_SECTIONS_TX_SECTION_FULL_E,
  /*41*/  AAS_MAC100_PMAC_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_E,
  /*42*/  AAS_MAC100_STATUS_RX_LOC_FAULT_E,
  /*43*/  AAS_MAC100_STATUS_RX_REM_FAULT_E,
  /*44*/  AAS_MAC100_STATUS_PHY_LOS_E,
  /*45*/  AAS_MAC100_STATUS_TS_AVAIL_E,
  /*46*/  AAS_MAC100_STATUS_RX_LOWP_E,
  /*47*/  AAS_MAC100_STATUS_PMAC_TX_EMPTY_E,
  /*48*/  AAS_MAC100_STATUS_PMAC_RX_EMPTY_E,
  /*49*/  AAS_MAC100_STATUS_RX_LINT_FAULT_E,
  /*50*/  AAS_MAC100_STATUS_TX_IS_IDLE_E,
  /*51*/  AAS_MAC100_STATUS_TX_MERGE_ISIDLE_E,
  /*52*/  AAS_MAC100_STATUS_EMAC_TX_EMPTY_E,
  /*53*/  AAS_MAC100_STATUS_EMAC_RX_EMPTY_E,
  /*54*/  AAS_MAC100_TX_IPG_LENGTH_ENABLE_SHORT_IPG_E,
  /*55*/  AAS_MAC100_TX_IPG_LENGTH_CMP_ALLOW_SHORT_IPG_E,
  /*56*/  AAS_MAC100_TX_IPG_LENGTH_TXIPG_RESERVED2_E,
  /*57*/  AAS_MAC100_TX_IPG_LENGTH_TXIPG_E,
  /*58*/  AAS_MAC100_TX_IPG_LENGTH_COMPENSATION_HI_E,
  /*59*/  AAS_MAC100_TX_IPG_LENGTH_COMPENSATION_E,
  /*60*/  AAS_MAC100_CRC_MODE_DISABLE_RX_CRC_CHECK_E,
  /*61*/  AAS_MAC100_CRC_MODE_CRC_1BYTE_E,
  /*62*/  AAS_MAC100_CRC_MODE_CRC_2BYTE_E,
  /*63*/  AAS_MAC100_CRC_MODE_CRC_0BYTE_E,
  /*64*/  AAS_MAC100_CRC_MODE_CRC_INV_E,
  /*65*/  AAS_MAC100_TS_TIMESTAMP_TS_TIMESTAMP_E,
  /*66*/  AAS_MAC100_XIF_MODE_XGMII_E,
  /*67*/  AAS_MAC100_XIF_MODE_PAUSETIMERX8_E,
  /*68*/  AAS_MAC100_XIF_MODE_ONESTEPENA_E,
  /*69*/  AAS_MAC100_XIF_MODE_EMAC_RX_PAUSE_BYPASS_E,
  /*70*/  AAS_MAC100_XIF_MODE_PMAC_RX_PAUSE_BYPASS_E,
  /*71*/  AAS_MAC100_XIF_MODE_TX_MAC_RS_ERR_E,
  /*72*/  AAS_MAC100_XIF_MODE_CFG_1STEP_DELTA_MODE_E,
  /*73*/  AAS_MAC100_XIF_MODE_CFG_1STEP_DELAY_MODE_E,
  /*74*/  AAS_MAC100_XIF_MODE_CFG_1STEP_BINARY_MODE_E,
  /*75*/  AAS_MAC100_XIF_MODE_CFG_1STEP_64UPD_MODE_E,
  /*76*/  AAS_MAC100_XIF_MODE_CFG_PFC_PULSE_MODE_E,
  /*77*/  AAS_MAC100_XIF_MODE_TS_SFD_ENA_E,
  /*78*/  AAS_MAC100_BR_CONTROL_TX_PREEMPT_EN_E,
  /*79*/  AAS_MAC100_BR_CONTROL_TX_VERIF_DIS_E,
  /*80*/  AAS_MAC100_BR_CONTROL_TX_ADDFRAGSIZE_E,
  /*81*/  AAS_MAC100_BR_CONTROL_TX_VERIFY_TIME_E,
  /*82*/  AAS_MAC100_BR_CONTROL_TX_PAUSE_PRI_EN_E,
  /*83*/  AAS_MAC100_BR_CONTROL_TX_FRAG_PAUSE_EN_E,
  /*84*/  AAS_MAC100_BR_CONTROL_TX_NON_EMPTY_PREEMPT_EN_E,
  /*85*/  AAS_MAC100_BR_CONTROL_TX_ALLOW_PMAC_IF_NVERIF_E,
  /*86*/  AAS_MAC100_BR_CONTROL_TX_ALLOW_EMAC_IF_NVERIF_E,
  /*87*/  AAS_MAC100_BR_CONTROL_BR_COUNT_CLR_ON_RD_E,
  /*88*/  AAS_MAC100_BR_CONTROL_BR_COUNT_SAT_E,
  /*89*/  AAS_MAC100_BR_CONTROL_RX_STRICT_PREAMBLE_E,
  /*90*/  AAS_MAC100_BR_CONTROL_PMAC_TO_EMAC_STATS_E,
  /*91*/  AAS_MAC100_BR_CONTROL_BR_RX_SMD_DIS_E,
  /*92*/  AAS_MAC100_BR_CONTROL_RX_BR_STRICT_FRM_ENA_E,
  /*93*/  AAS_MAC100_BR_STATUS_TX_VERIFY_STATUS_E,
  /*94*/  AAS_MAC100_BR_STATUS_TX_PREEMPT_STATUS_E,
  /*95*/  AAS_MAC100_BR_STATUS_ASSY_ERR_LH_E,
  /*96*/  AAS_MAC100_BR_STATUS_SMD_ERR_LH_E,
  /*97*/  AAS_MAC100_BR_STATUS_VERIF_SEEN_LH_E,
  /*98*/  AAS_MAC100_BR_STATUS_RESP_SEEN_LH_E,
  /*99*/  AAS_MAC100_BR_TX_FRAG_COUNT_TX_FRAG_COUNT_E,
  /*100*/  AAS_MAC100_BR_RX_FRAG_COUNT_RX_FRAG_COUNT_E,
  /*101*/  AAS_MAC100_BR_TX_HOLD_COUNT_TX_HOLD_COUNT_E,
  /*102*/  AAS_MAC100_BR_RX_SMD_ERR_COUNT_RX_SMD_ERR_COUNT_E,
  /*103*/  AAS_MAC100_BR_RX_ASSY_ERR_COUNT_RX_ASSY_ERR_COUNT_E,
  /*104*/  AAS_MAC100_BR_RX_ASSY_OK_COUNT_RX_ASSY_OK_COUNT_E,
  /*105*/  AAS_MAC100_BR_RX_VERIFY_COUNT_RX_VERIFY_COUNT_GOOD_E,
  /*106*/  AAS_MAC100_BR_RX_VERIFY_COUNT_RX_VERIFY_COUNT_BAD_E,
  /*107*/  AAS_MAC100_BR_RX_RESPONSE_COUNT_RX_RESP_COUNT_GOOD_E,
  /*108*/  AAS_MAC100_BR_RX_RESPONSE_COUNT_RX_RESP_COUNT_BAD_E,
  /*109*/  AAS_MAC100_BR_TX_VERIF_COUNT_TX_VERIF_COUNT_E,
  /*110*/  AAS_MAC100_BR_TX_VERIF_COUNT_TX_RESP_COUNT_E,
  /*111*/  AAS_MAC100_EMAC_COMMAND_CONFIG_TX_ENA_E,
  /*112*/  AAS_MAC100_EMAC_COMMAND_CONFIG_RX_ENA_E,
  /*113*/  AAS_MAC100_EMAC_COMMAND_CONFIG_PAUSE_FWD_E,
  /*114*/  AAS_MAC100_EMAC_COMMAND_CONFIG_PAUSE_IGNORE_E,
  /*115*/  AAS_MAC100_EMAC_COMMAND_CONFIG_TX_ADDR_INS_E,
  /*116*/  AAS_MAC100_EMAC_COMMAND_CONFIG_SW_RESET_E,
  /*117*/  AAS_MAC100_EMAC_COMMAND_CONFIG_CNTL_FRAME_ENA_E,
  /*118*/  AAS_MAC100_EMAC_COMMAND_CONFIG_EMAC_PAUSE_MASK_P_E,
  /*119*/  AAS_MAC100_EMAC_COMMAND_CONFIG_EMAC_PAUSE_MASK_E_E,
  /*120*/  AAS_MAC100_EMAC_COMMAND_CONFIG_PFC_MODE_E,
  /*121*/  AAS_MAC100_EMAC_COMMAND_CONFIG_PAUSE_PFC_COMP_E,
  /*122*/  AAS_MAC100_EMAC_COMMAND_CONFIG_TX_FLUSH_E,
  /*123*/  AAS_MAC100_EMAC_COMMAND_CONFIG_TX_FIFO_RESET_E,
  /*124*/  AAS_MAC100_EMAC_COMMAND_CONFIG_EMAC_TX_PAUSE_DIS_E,
  /*125*/  AAS_MAC100_EMAC_COMMAND_CONFIG_EMAC_RX_PAUSE_DIS_E,
  /*126*/  AAS_MAC100_EMAC_MAC_ADDR_0_MAC_ADDRESS_0_E,
  /*127*/  AAS_MAC100_EMAC_MAC_ADDR_1_MAC_ADDRESS_1_E,
  /*128*/  AAS_MAC100_EMAC_FRM_LENGTH_FRM_LENGTH_E,
  /*129*/  AAS_MAC100_EMAC_FRM_LENGTH_TX_MTU_E,
  /*130*/  AAS_MAC100_EMAC_RX_FIFO_SECTIONS_RX_SECTION_FULL_E,
  /*131*/  AAS_MAC100_EMAC_RX_FIFO_SECTIONS_RX_SECTION_EMPTY_E,
  /*132*/  AAS_MAC100_EMAC_TX_FIFO_SECTIONS_TX_SECTION_FULL_E,
  /*133*/  AAS_MAC100_EMAC_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_E,
  /*134*/  AAS_MAC100_EMAC_CL01_PAUSE_QUANTA_CL0_PAUSE_QUANTA_E,
  /*135*/  AAS_MAC100_EMAC_CL01_PAUSE_QUANTA_CL1_PAUSE_QUANTA_E,
  /*136*/  AAS_MAC100_EMAC_CL23_PAUSE_QUANTA_CL2_PAUSE_QUANTA_E,
  /*137*/  AAS_MAC100_EMAC_CL23_PAUSE_QUANTA_CL3_PAUSE_QUANTA_E,
  /*138*/  AAS_MAC100_EMAC_CL45_PAUSE_QUANTA_CL4_PAUSE_QUANTA_E,
  /*139*/  AAS_MAC100_EMAC_CL45_PAUSE_QUANTA_CL5_PAUSE_QUANTA_E,
  /*140*/  AAS_MAC100_EMAC_CL67_PAUSE_QUANTA_CL6_PAUSE_QUANTA_E,
  /*141*/  AAS_MAC100_EMAC_CL67_PAUSE_QUANTA_CL7_PAUSE_QUANTA_E,
  /*142*/  AAS_MAC100_EMAC_CL01_QUANTA_THRESH_CL0_QUANTA_THRESH_E,
  /*143*/  AAS_MAC100_EMAC_CL01_QUANTA_THRESH_CL1_QUANTA_THRESH_E,
  /*144*/  AAS_MAC100_EMAC_CL23_QUANTA_THRESH_CL2_QUANTA_THRESH_E,
  /*145*/  AAS_MAC100_EMAC_CL23_QUANTA_THRESH_CL3_QUANTA_THRESH_E,
  /*146*/  AAS_MAC100_EMAC_CL45_QUANTA_THRESH_CL4_QUANTA_THRESH_E,
  /*147*/  AAS_MAC100_EMAC_CL45_QUANTA_THRESH_CL5_QUANTA_THRESH_E,
  /*148*/  AAS_MAC100_EMAC_CL67_QUANTA_THRESH_CL6_QUANTA_THRESH_E,
  /*149*/  AAS_MAC100_EMAC_CL67_QUANTA_THRESH_CL7_QUANTA_THRESH_E,
  /*150*/  AAS_MAC100_EMAC_RX_PAUSE_STATUS_EMAC_RX_PAUSE_STATUS_E,
           AAS_MAC100_REGISTER_LAST_E /* should be last */
} MV_HWS_AAS_MAC100_UNIT_FIELDS_ENT;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsAasMac100Units_H */

