/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAasCpuPcsExtUnits.h
*
* @brief AAS CPU PCS EXT interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAasCpuPcsExtUnits_H
#define __mvHwsAasCpuPcsExtUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  AAS_CPU_PCS_EXT_GLOBAL_PMA_CONTROL_GC_SD_8X_E,
  /*1*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CONTROL_GC_FEC_ENA_E,
  /*2*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CONTROL_GC_FEC_ERR_ENA_E,
  /*3*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CONTROL_GC_FEC91_ENA_IN_E,
  /*4*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CONTROL_GC_KP_MODE_IN_E,
  /*5*/  AAS_CPU_PCS_EXT_GLOBAL_CHANNEL_CONTROL_BER_TIMER_SHORT_E,
  /*6*/  AAS_CPU_PCS_EXT_GLOBAL_CHANNEL_CONTROL_PCS_ABU_WATCHDOG_ENA_E,
  /*7*/  AAS_CPU_PCS_EXT_GLOBAL_CHANNEL_CONTROL_CYC_TO_STRETCH_MAC2REG_E,
  /*8*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_CONTROL_GC_FAST_1LANE_MODE_E,
  /*9*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_CONTROL_GC_PACER_10G_E,
  /*10*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_ENABLE_MAC_CLK_EN_E,
  /*11*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_ENABLE_MAC_CMN_CLK_EN_E,
  /*12*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_ENABLE_FEC91_CLK_EN_E,
  /*13*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_ENABLE_XPCS_CLK_EN_E,
  /*14*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_ENABLE_SGREF_CLK_EN_E,
  /*15*/  AAS_CPU_PCS_EXT_GLOBAL_CLOCK_ENABLE_MAC_MAC_CMN_CLK_EN_E,
  /*16*/  AAS_CPU_PCS_EXT_GLOBAL_RESET_CONTROL_GC_SD_RX_RESET_E,
  /*17*/  AAS_CPU_PCS_EXT_GLOBAL_RESET_CONTROL_GC_SD_TX_RESET_E,
  /*18*/  AAS_CPU_PCS_EXT_GLOBAL_RESET_CONTROL_GC_XPCS_RESET_E,
  /*19*/  AAS_CPU_PCS_EXT_GLOBAL_RESET_CONTROL_GC_F91_RESET_E,
  /*20*/  AAS_CPU_PCS_EXT_GLOBAL_RESET_CONTROL_GC_SG_RESET_E,
  /*21*/  AAS_CPU_PCS_EXT_GLOBAL_RESET_CONTROL2_GC_MAC_MAC_CMN_RESET_E,
  /*22*/  AAS_CPU_PCS_EXT_GLOBAL_AMPS_LOCK_STATUS_AMPS_LOCK_E,
  /*23*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_STATUS_FEC_LOCKED_E,
  /*24*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_ERROR_STATUS_FEC_CERR_E,
  /*25*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_ERROR_STATUS_FEC_NCERR_E,
  /*26*/  AAS_CPU_PCS_EXT_GLOBAL_BLOCK_LOCK_STATUS0_BLOCK_LOCK0_E,
  /*27*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_CAUSE_GLOBAL_INTERRUPT_CAUSE_INT_SUM_E,
  /*28*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_E,
  /*29*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_MASK_GLOBAL_INTERRUPT_MASK_E,
  /*30*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CE_INTERRUPT_CAUSE_FEC_CE_INTERRUPT_CAUSE_INT_SUM_E,
  /*31*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CE_INTERRUPT_CAUSE_FEC_CE_0_E,
  /*32*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_CE_INTERRUPT_MASK_FEC_CE_INTERRUPT_MASK_E,
  /*33*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_NCE_INTERRUPT_CAUSE_FEC_NCE_INTERRUPT_CAUSE_INT_SUM_E,
  /*34*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_NCE_INTERRUPT_CAUSE_FEC_NCE_0_E,
  /*35*/  AAS_CPU_PCS_EXT_GLOBAL_FEC_NCE_INTERRUPT_MASK_FEC_NCE_INTERRUPT_MASK_E,
  /*36*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_GLOBAL_INTERRUPT_SUMMARY_INT_SUM_E,
  /*37*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P0_INT_SUM_E,
  /*38*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_GLOBAL_INT_SUM_E,
  /*39*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_FEC_CE_INT_SUM_E,
  /*40*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_FEC_NCE_INT_SUM_E,
  /*41*/  AAS_CPU_PCS_EXT_GLOBAL_INTERRUPT_SUMMARY_MASK_GLOBAL_INTERRUPT_SUMMARY_MASK_E,
  /*42*/  AAS_CPU_PCS_EXT_LAST_VIOLATION_LAST_VIOLATION_E,
  /*43*/  AAS_CPU_PCS_EXT_GLOBAL_PCS_METAL_FIX_PCS_METAL_FIX_E,
  /*44*/  AAS_CPU_PCS_EXT_PORT_STATUS_XL_LINK_STATUS_E,
  /*45*/  AAS_CPU_PCS_EXT_PORT_STATUS_LPCS_LINK_STATUS_E,
  /*46*/  AAS_CPU_PCS_EXT_PORT_STATUS_LPCS_RX_SYNC_E,
  /*47*/  AAS_CPU_PCS_EXT_PORT_STATUS_LPCS_AN_DONE_E,
  /*48*/  AAS_CPU_PCS_EXT_PORT_STATUS_XL_HI_BER_E,
  /*49*/  AAS_CPU_PCS_EXT_PORT_STATUS_RSFEC_ALIGNED_E,
  /*50*/  AAS_CPU_PCS_EXT_PORT_STATUS_XL_LINK_STATUS_CLEAN_E,
  /*51*/  AAS_CPU_PCS_EXT_PORT_STATUS_LPCS_LINK_STATUS_CLEAN_E,
  /*52*/  AAS_CPU_PCS_EXT_PORT_INTERRUPT_CAUSE_INTERRUPT_CAUSE_INT_SUM_E,
  /*53*/  AAS_CPU_PCS_EXT_PORT_INTERRUPT_CAUSE_XL_LINK_STATUS_CHANGE_E,
  /*54*/  AAS_CPU_PCS_EXT_PORT_INTERRUPT_CAUSE_LPCS_LINK_STATUS_CHANGE_E,
  /*55*/  AAS_CPU_PCS_EXT_PORT_INTERRUPT_CAUSE_HI_BER_E,
  /*56*/  AAS_CPU_PCS_EXT_PORT_INTERRUPT_MASK_INTERRUPT_MASK_E,
  /*57*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_RF_TX_LANE_THRESH_E,
  /*58*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_FORCE_LINK_STATUS_EN_E,
  /*59*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_FORCE_LINK_STATUS_DIS_E,
  /*60*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_FORCE_LPCS_LINK_STATUS_EN_E,
  /*61*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_FORCE_LPCS_LINK_STATUS_DIS_E,
  /*62*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_FORCE_XL_LINK_STATUS_EN_E,
  /*63*/  AAS_CPU_PCS_EXT_PORT_CONTROL1_FORCE_XL_LINK_STATUS_DIS_E,
  /*64*/  AAS_CPU_PCS_EXT_PCS_ABU_WATCHDOG_MAX_TIMER_PCS_ABU_WATCHDOG_MAX_TIMER_E,
  /*65*/  AAS_CPU_PCS_EXT_PORT_STATUS_2_SD_BIT_SLIP_E,
          AAS_CPU_PCS_EXT_REGISTER_LAST_E /* should be last */
} MV_HWS_AAS_CPU_PCS_EXT_UNIT_FIELDS_ENT;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsAasCpuPcsExtUnits_H */

