/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAc5xRsfecStatisticsUnits.h
*
* @brief Ac5x port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAc5xRsfecStatisticsUnits_H
#define __mvHwsAc5xRsfecStatisticsUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
   /*0 */   PHOENIX_RSFEC_STATISTICS_FAST_DATA_HI_LATCHED_COUNTER_HI_FAST_E,
  /*1 */   PHOENIX_RSFEC_STATISTICS_STATN_STATUS_STAT_MODULE_BUSY_E,
  /*2 */   PHOENIX_RSFEC_STATISTICS_STATN_CONFIG_SATURATE_E,
  /*3 */   PHOENIX_RSFEC_STATISTICS_STATN_CONFIG_CLEAR_ON_READ_E,
  /*4 */   PHOENIX_RSFEC_STATISTICS_STATN_CONFIG_SOFT_RESET_E,
  /*5 */   PHOENIX_RSFEC_STATISTICS_STATN_CONTROL_E,
  /*6 */   PHOENIX_RSFEC_STATISTICS_STATN_CONTROL_CHANMASK_E,
  /*7 */   PHOENIX_RSFEC_STATISTICS_STATN_CONTROL_CMD_CAPTURE_E,
  /*8 */   PHOENIX_RSFEC_STATISTICS_STATN_CONTROL_CLEAR_PRE_E,
  /*9 */   PHOENIX_RSFEC_STATISTICS_STATN_CONTROL_CMD_CLEAR_E,
  /*10*/   PHOENIX_RSFEC_STATISTICS_STATN_CLEARVALUE_LO_STATM_LOWER_32B_E,
  /*11*/  PHOENIX_RSFEC_STATISTICS_STATN_CLEARVALUE_HI_STATM_HIGH_32B_E,
  /*12*/  PHOENIX_RSFEC_STATISTICS_SLOW_DATA_HI_LATCHED_DATA_HI_SLOW_E,
  /*13*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_TOTAL_CODEWORDS_RECEIVED_TOTAL_CW_RECEIVED_E,
  /*14*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_TOTAL_CODEWORDS_CORRECT_TOTAL_CW_CORRECT_E,
  /*15*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_TOTAL_CODEWORDS_CORRECTED_TOTAL_CW_CORRECTED_E,
  /*16*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_TOTAL_CODEWORDS_UNCORRECTABLE_TOTAL_CW_UNCORRECTABLE_E,
  /*17*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_1SE_CW_CORRECTED_1SE_E,
  /*18*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_2SE_CW_CORRECTED_2SE_E,
  /*19*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_3SE_CW_CORRECTED_3SE_E,
  /*20*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_4SE_CW_CORRECTED_4SE_E,
  /*21*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_5SE_CW_CORRECTED_5SE_E,
  /*22*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_6SE_CW_CORRECTED_6SE_E,
  /*23*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_7SE_CW_CORRECTED_7SE_E,
  /*24*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_8SE_CW_CORRECTED_8SE_E,
  /*25*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_9SE_CW_CORRECTED_9SE_E,
  /*26*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_10SE_CW_CORRECTED_10SE_E,
  /*27*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_11SE_CW_CORRECTED_11SE_E,
  /*28*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_12SE_CW_CORRECTED_12SE_E,
  /*29*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_13SE_CW_CORRECTED_13SE_E,
  /*30*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_14SE_CW_CORRECTED_14SE_E,
  /*31*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_CODEWORDS_CORRECTED_15SE_CW_CORRECTED_15SE_E,
  /*32*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE0_E,
  /*33*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE1_E,
  /*34*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE2_E,
  /*35*/  PHOENIX_RSFEC_STATISTICS_COUNTER_CAPTURE_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE3_E,
  /*36*/  PHOENIX_RSFEC_STATISTICS_TOTAL_CODEWORDS_RECEIVED_TOTAL_CW_RECEIVED_E,
  /*37*/  PHOENIX_RSFEC_STATISTICS_TOTAL_CODEWORDS_CORRECT_TOTAL_CW_CORRECT_E,
  /*38*/  PHOENIX_RSFEC_STATISTICS_TOTAL_CODEWORDS_CORRECTED_TOTAL_CW_CORRECTED_E,
  /*39*/  PHOENIX_RSFEC_STATISTICS_TOTAL_CODEWORDS_UNCORRECTABLE_TOTAL_CW_UNCORRECTABLE_E,
  /*40*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_1SE_CW_CORRECTED_1SE_E,
  /*41*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_2SE_CW_CORRECTED_2SE_E,
  /*42*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_3SE_CW_CORRECTED_3SE_E,
  /*43*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_4SE_CW_CORRECTED_4SE_E,
  /*44*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_5SE_CW_CORRECTED_5SE_E,
  /*45*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_6SE_CW_CORRECTED_6SE_E,
  /*46*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_7SE_CW_CORRECTED_7SE_E,
  /*47*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_8SE_CW_CORRECTED_8SE_E,
  /*48*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_9SE_CW_CORRECTED_9SE_E,
  /*49*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_10SE_CW_CORRECTED_10SE_E,
  /*50*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_11SE_CW_CORRECTED_11SE_E,
  /*51*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_12SE_CW_CORRECTED_12SE_E,
  /*52*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_13SE_CW_CORRECTED_13SE_E,
  /*53*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_14SE_CW_CORRECTED_14SE_E,
  /*54*/  PHOENIX_RSFEC_STATISTICS_CODEWORDS_CORRECTED_15SE_CW_CORRECTED_15SE_E,
  /*55*/  PHOENIX_RSFEC_STATISTICS_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE0_E,
  /*56*/  PHOENIX_RSFEC_STATISTICS_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE1_E,
  /*57*/  PHOENIX_RSFEC_STATISTICS_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE2_E,
  /*58*/  PHOENIX_RSFEC_STATISTICS_SYMBOL_ERROR_CORRECTED_LANE0_SE_CORRECTED_LANE3_E,

    PHOENIX_RSFEC_STATISTICS_REGISTER_LAST_E /* should be last */
} MV_HWS_PHOENIX_RSFEC_STATISTICS_UNITS_FIELDS_ENT;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsAc5xRsfecStatisticsUnits_H */
