#!/bin/sh
. /etc/init.d/functions
case "$1" in
		start)
				echo "Starting quagga daemon..."
				zebra -f /etc/zebra.conf -u root -g root -d
				evaluate_retval
				echo "Starting sysmon daemon..."
				sysmon -u root -g root -d
				evaluate_retval
				;;
		stop)
				echo "Stopping quagga daemon..."
				killproc zebra
				echo "Stopping sysmon daemon..."
				killproc sysmon
				;;
		restart)
				$0 stop
				sleep 1
				$0 start
				;;
		status)
				statusproc zebra
				;;
		*)
				echo "Usage: $0 {start|stop|reload|restart|status}"
				exit 1
				;;
esac
exit 0
