/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,     *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*
* prvCpssAasTxqSdqRegFile.h
*
*Automaticly generated from :
*
* DESCRIPTION:
*      Describe TXQ SDQ registers (Automaticly generated from CIDER)
*
* DEPENDENCIES:
*       None.
*
* FILE REVISION NUMBER:
*       $Revision: 1 $
*
*******************************************************************************/
#ifndef _TXQ_AAS__SDQ_REGFILE_H_
#define _TXQ_AAS__SDQ_REGFILE_H_

/* start of register global_config*/

#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_AGING_EN_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_MSG_CNCL_EN_FIELD_OFFSET         1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_SELIG_EN_FIELD_OFFSET            2
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_SELIG4DRY_EN_FIELD_OFFSET            3
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_SELIG_1K_EN_FIELD_OFFSET         4
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_QPKT_EN_FIELD_OFFSET         5
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_QBV_SCAN_EN_FIELD_OFFSET         6


#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_AGING_EN_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_MSG_CNCL_EN_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_SELIG_EN_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_SELIG4DRY_EN_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_SELIG_1K_EN_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_QPKT_EN_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_GLOBAL_CONFIG_QBV_SCAN_EN_FIELD_SIZE           1

/* end of global_config*/


/* start of register SDQ_Metal_Fix*/

#define      TXQ_AAS_SDQ_SDQ_METAL_FIX_SDQ_METAL_FIX_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_SDQ_METAL_FIX_SDQ_METAL_FIX_FIELD_SIZE         32

/* end of SDQ_Metal_Fix*/


/* start of register SDQ_Interrupt_Functional_Cause*/

#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_SDQ_FUNC_INTSUM_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_OFFSET         1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_ILLEGAL_TABLE_OVERLAP_FIELD_OFFSET          2
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_CRDT_FIELD_OFFSET           3
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_ENQ_FIELD_OFFSET            4
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_DEQ_FIELD_OFFSET            5
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_QCN_FIELD_OFFSET            6
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_CRDT_FIELD_OFFSET            7
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_ENQ_FIELD_OFFSET         8
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_DEQ_FIELD_OFFSET         9
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_QCN_FIELD_OFFSET         10
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_PFC_FIELD_OFFSET         11
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_SEL_FIELD_OFFSET         12
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_SEL_PORT_OUTOFRANGE_FIELD_OFFSET            13


#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_SDQ_FUNC_INTSUM_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_ILLEGAL_TABLE_OVERLAP_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_CRDT_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_ENQ_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_DEQ_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_QUEUE_QCN_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_CRDT_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_ENQ_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_DEQ_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_QCN_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_PFC_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_UNMAP_PORT_SEL_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_CAUSE_SEL_PORT_OUTOFRANGE_FIELD_SIZE          1

/* end of SDQ_Interrupt_Functional_Cause*/


/* start of register sdq_interrupt_functional_mask*/

#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK0_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK1_FIELD_OFFSET            2
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK2_FIELD_OFFSET            3
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK3_FIELD_OFFSET            4
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK4_FIELD_OFFSET            5
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK5_FIELD_OFFSET            6
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK6_FIELD_OFFSET            7
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK7_FIELD_OFFSET            8
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK8_FIELD_OFFSET            9
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK9_FIELD_OFFSET            10
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK10_FIELD_OFFSET           11
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK11_FIELD_OFFSET           12
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK12_FIELD_OFFSET           13


#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK0_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK1_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK2_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK3_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK4_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK5_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK6_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK7_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK8_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK9_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK10_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK11_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_FUNCTIONAL_MASK_SDQ_FUNC_INT_CAUSE_MASK12_FIELD_SIZE         1

/* end of sdq_interrupt_functional_mask*/


/* start of register SDQ_Interrupt_Summary_Mask*/

#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_MASK_SDQ_INT_SUM_MASK0_FIELD_OFFSET          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_MASK_SDQ_INT_SUM_MASK1_FIELD_OFFSET          2


#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_MASK_SDQ_INT_SUM_MASK0_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_MASK_SDQ_INT_SUM_MASK1_FIELD_SIZE            1

/* end of SDQ_Interrupt_Summary_Mask*/


/* start of register SDQ_Interrupt_Summary_Cause*/

#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_CAUSE_SDQ_INT_SUM_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_CAUSE_SDQ_FUNC_INT_SUM_FIELD_OFFSET          1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_CAUSE_SDQ_DBG_INT_SUM_FIELD_OFFSET           2


#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_CAUSE_SDQ_INT_SUM_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_CAUSE_SDQ_FUNC_INT_SUM_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_SUMMARY_CAUSE_SDQ_DBG_INT_SUM_FIELD_SIZE         1

/* end of SDQ_Interrupt_Summary_Cause*/


/* start of register SDQ_Interrupt_Debug_Mask*/

#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_DEBUG_MASK_SDQ_DEBUG_INT_CAUSE_MASK0_FIELD_OFFSET            1


#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_DEBUG_MASK_SDQ_DEBUG_INT_CAUSE_MASK0_FIELD_SIZE          1

/* end of SDQ_Interrupt_Debug_Mask*/


/* start of register SDQ_Interrupt_Debug_Cause*/

#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_DEBUG_CAUSE_SDQ_DBG_INTSUM_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_DEBUG_CAUSE_QCN_FIFO_OVERRUN_FIELD_OFFSET            1


#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_DEBUG_CAUSE_SDQ_DBG_INTSUM_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_SDQ_INTERRUPT_DEBUG_CAUSE_QCN_FIFO_OVERRUN_FIELD_SIZE          1

/* end of SDQ_Interrupt_Debug_Cause*/


/* start of register Port_Back_Pressure_Low_Threshold*/

#define      TXQ_AAS_SDQ_PORT_BACK_PRESSURE_LOW_THRESHOLD_PORT_BP_LOW_TH_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PORT_BACK_PRESSURE_LOW_THRESHOLD_PORT_BP_LOW_TH_FIELD_SIZE         31

/* end of Port_Back_Pressure_Low_Threshold*/


/* start of register Port_Back_Pressure_High_Threshold*/

#define      TXQ_AAS_SDQ_PORT_BACK_PRESSURE_HIGH_THRESHOLD_PORT_BP_HIGH_TH_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PORT_BACK_PRESSURE_HIGH_THRESHOLD_PORT_BP_HIGH_TH_FIELD_SIZE           31

/* end of Port_Back_Pressure_High_Threshold*/


/* start of register Port_Config*/

#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_EN_0_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_BP_EN_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_PORT_CONFIG_CRDT_IGN_0_FIELD_OFFSET            2
#define      TXQ_AAS_SDQ_PORT_CONFIG_QDRYER_SELIG_TH0_0_FIELD_OFFSET            3
#define      TXQ_AAS_SDQ_PORT_CONFIG_QDRYER_SELIG_TH1_0_FIELD_OFFSET            8
#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_GLBL_SLCT_EN_0_FIELD_OFFSET           13
#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_TYPE_PRMPT_0_FIELD_OFFSET         14


#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_EN_0_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_BP_EN_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_CONFIG_CRDT_IGN_0_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_CONFIG_QDRYER_SELIG_TH0_0_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_PORT_CONFIG_QDRYER_SELIG_TH1_0_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_GLBL_SLCT_EN_0_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_CONFIG_PORT_TYPE_PRMPT_0_FIELD_SIZE           1

/* end of Port_Config*/


/* start of register QCN_Config*/

#define      TXQ_AAS_SDQ_QCN_CONFIG_QCN_FRQ_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_QCN_CONFIG_QCN_FRQ_FIELD_SIZE          2

/* end of QCN_Config*/


/* start of register PFC_Control*/

#define      TXQ_AAS_SDQ_PFC_CONTROL_TC_EN0_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_PFC_CONTROL_TC_EN0_FIELD_SIZE          16

/* end of PFC_Control*/


/* start of register Pause_TC*/

#define      TXQ_AAS_SDQ_PAUSE_TC_PAUSE_TC_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PAUSE_TC_PAUSE_TC_0_FIELD_SIZE         16

/* end of Pause_TC*/


/* start of register Sdq_Idle*/

#define      TXQ_AAS_SDQ_SDQ_IDLE_SDQ_IDLE_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_TOP_IDLE_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_STGS_IDLE_FIELD_OFFSET           2
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_STGD_IDLE_FIELD_OFFSET           3
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_STGQ_IDLE_FIELD_OFFSET           4
#define      TXQ_AAS_SDQ_SDQ_IDLE_QDRYER_IDLE_FIELD_OFFSET          5
#define      TXQ_AAS_SDQ_SDQ_IDLE_SEL_IDLE_FIELD_OFFSET         6
#define      TXQ_AAS_SDQ_SDQ_IDLE_MSG_IDLE_FIELD_OFFSET         7
#define      TXQ_AAS_SDQ_SDQ_IDLE_PORTS_QBV_IDLE_FIELD_OFFSET           8
#define      TXQ_AAS_SDQ_SDQ_IDLE_GLOBAL_PORT_IDLE_FIELD_OFFSET         9


#define      TXQ_AAS_SDQ_SDQ_IDLE_SDQ_IDLE_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_TOP_IDLE_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_STGS_IDLE_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_STGD_IDLE_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_IDLE_ELIG_STGQ_IDLE_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_IDLE_QDRYER_IDLE_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_SDQ_IDLE_SEL_IDLE_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_IDLE_MSG_IDLE_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SDQ_IDLE_PORTS_QBV_IDLE_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SDQ_IDLE_GLOBAL_PORT_IDLE_FIELD_SIZE           1

/* end of Sdq_Idle*/


/* start of register Illegal_Bad_Address*/

#define      TXQ_AAS_SDQ_ILLEGAL_BAD_ADDRESS_BAD_ADDRESS_CAPTURE_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_ILLEGAL_BAD_ADDRESS_BAD_ADDRESS_CAPTURE_FIELD_SIZE         32

/* end of Illegal_Bad_Address*/


/* start of register QCN_Message_Drop_Counter*/

#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_QCN_MSG_DRP_CNT_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_QCN_MSG_DRP_CNT_FIELD_SIZE            32

/* end of QCN_Message_Drop_Counter*/


/* start of register Queue_Dryer_FIFO_Max_Peak*/

#define      TXQ_AAS_SDQ_QUEUE_DRYER_FIFO_MAX_PEAK_DRYER_FIFO_MAX_PEAK_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_QUEUE_DRYER_FIFO_MAX_PEAK_DRYER_FIFO_MAX_PEAK_FIELD_SIZE           13

/* end of Queue_Dryer_FIFO_Max_Peak*/


/* start of register PDQ_Message_Output_FIFO_Max_Peak*/

#define      TXQ_AAS_SDQ_PDQ_MESSAGE_OUTPUT_FIFO_MAX_PEAK_MSG_FIFO_MAX_PEAK_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_PDQ_MESSAGE_OUTPUT_FIFO_MAX_PEAK_MSG_FIFO_MAX_PEAK_FIELD_SIZE          13

/* end of PDQ_Message_Output_FIFO_Max_Peak*/


/* start of register QCN_Message_Drop_Counter_Control*/

#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_CONTROL_QCN_MSG_DROP_TRIG_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_CONTROL_QCN_MSG_DROP_QUEUE_FIELD_OFFSET           2
#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_CONTROL_QCN_MSG_DROP_PORT_FIELD_OFFSET            17


#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_CONTROL_QCN_MSG_DROP_TRIG_FIELD_SIZE          2
#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_CONTROL_QCN_MSG_DROP_QUEUE_FIELD_SIZE         15
#define      TXQ_AAS_SDQ_QCN_MESSAGE_DROP_COUNTER_CONTROL_QCN_MSG_DROP_PORT_FIELD_SIZE          6

/* end of QCN_Message_Drop_Counter_Control*/


/* start of register QCN_Message_FIFO_Max_Peak*/

#define      TXQ_AAS_SDQ_QCN_MESSAGE_FIFO_MAX_PEAK_QCN_MSG_FIFO_MAX_PEAK_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_QCN_MESSAGE_FIFO_MAX_PEAK_QCN_MSG_FIFO_MAX_PEAK_FIELD_SIZE         6

/* end of QCN_Message_FIFO_Max_Peak*/


/* start of register QCN_Message_FIFO_Fill_Level*/

#define      TXQ_AAS_SDQ_QCN_MESSAGE_FIFO_FILL_LEVEL_QCN_MSG_FIFO_FILL_LEVEL_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_QCN_MESSAGE_FIFO_FILL_LEVEL_QCN_MSG_FIFO_FILL_LEVEL_FIELD_SIZE         6

/* end of QCN_Message_FIFO_Fill_Level*/


/* start of register Elig_Func_Error_Capture*/

#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_QUEUE_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_PORT_FIELD_OFFSET           15
#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_SRC_FIELD_OFFSET            21
#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_VALID_FIELD_OFFSET          24


#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_QUEUE_FIELD_SIZE            15
#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_PORT_FIELD_SIZE         6
#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_SRC_FIELD_SIZE          3
#define      TXQ_AAS_SDQ_ELIG_FUNC_ERROR_CAPTURE_ELIG_ERROR_VALID_FIELD_SIZE            1

/* end of Elig_Func_Error_Capture*/


/* start of register Select_Func_Error_Capture*/

#define      TXQ_AAS_SDQ_SELECT_FUNC_ERROR_CAPTURE_SEL_ERROR_PORT_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_SELECT_FUNC_ERROR_CAPTURE_SEL_ERROR_VALID_FIELD_OFFSET         6


#define      TXQ_AAS_SDQ_SELECT_FUNC_ERROR_CAPTURE_SEL_ERROR_PORT_FIELD_SIZE            6
#define      TXQ_AAS_SDQ_SELECT_FUNC_ERROR_CAPTURE_SEL_ERROR_VALID_FIELD_SIZE           1

/* end of Select_Func_Error_Capture*/


/* start of register debug_config*/

#define      TXQ_AAS_SDQ_DEBUG_CONFIG_ENABLE_DEBUG_GROUP_COUNTING_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_DEBUG_CONFIG_COUNT_USING_TIMER_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_DEBUG_CONFIG_COUNT_ROC_FIELD_OFFSET            2


#define      TXQ_AAS_SDQ_DEBUG_CONFIG_ENABLE_DEBUG_GROUP_COUNTING_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_DEBUG_CONFIG_COUNT_USING_TIMER_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_DEBUG_CONFIG_COUNT_ROC_FIELD_SIZE          1

/* end of debug_config*/


/* start of register enable_debug_counters*/

#define      TXQ_AAS_SDQ_ENABLE_DEBUG_COUNTERS_ENABLE_DEBUG_COUNTERS_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_ENABLE_DEBUG_COUNTERS_ENABLE_DEBUG_COUNTERS_FIELD_SIZE         1

/* end of enable_debug_counters*/


/* start of register debug_cycles_to_count_lsb*/

#define      TXQ_AAS_SDQ_DEBUG_CYCLES_TO_COUNT_LSB_CYCLES_TO_COUNT_LSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_DEBUG_CYCLES_TO_COUNT_LSB_CYCLES_TO_COUNT_LSB_FIELD_SIZE           32

/* end of debug_cycles_to_count_lsb*/


/* start of register debug_cycles_to_count_msb*/

#define      TXQ_AAS_SDQ_DEBUG_CYCLES_TO_COUNT_MSB_CYCLES_TO_COUNT_MSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_DEBUG_CYCLES_TO_COUNT_MSB_CYCLES_TO_COUNT_MSB_FIELD_SIZE           32

/* end of debug_cycles_to_count_msb*/


/* start of register sel_if_cnt_lsb*/

#define      TXQ_AAS_SDQ_SEL_IF_CNT_LSB_SEL_IF_CNT_LSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_SEL_IF_CNT_LSB_SEL_IF_CNT_LSB_FIELD_SIZE           32

/* end of sel_if_cnt_lsb*/


/* start of register Select_IF_Count_Type_Ref1*/

#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF1_SELECT_COUNT_REF_MAX_ALLOWED_BC_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF1_SELECT_COUNT_REF_MAX_ALLOWED_BC_FIELD_SIZE           14

/* end of Select_IF_Count_Type_Ref1*/


/* start of register Select_IF_Count_Type_Mask1*/

#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK1_SELECT_COUNT_MASK_MAX_ALLOWED_BC_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK1_SELECT_COUNT_MASK_MAX_ALLOWED_BC_FIELD_SIZE         14

/* end of Select_IF_Count_Type_Mask1*/


/* start of register sel_if_cnt_msb*/

#define      TXQ_AAS_SDQ_SEL_IF_CNT_MSB_SEL_IF_CNT_MSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_SEL_IF_CNT_MSB_SEL_IF_CNT_MSB_FIELD_SIZE           32

/* end of sel_if_cnt_msb*/


/* start of register Select_IF_Count_Type_Ref0*/

#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_QUEUE_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_PORT_FIELD_OFFSET           15
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_QUEUE_SEL_FIELD_OFFSET          21
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_PRIO_REQ_FIELD_OFFSET           22
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_PRIO_RES_FIELD_OFFSET           23
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_NULL_ATTR_FIELD_OFFSET          24


#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_QUEUE_FIELD_SIZE            15
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_PORT_FIELD_SIZE         6
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_QUEUE_SEL_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_PRIO_REQ_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_PRIO_RES_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_REF0_SELECT_COUNT_REF_NULL_ATTR_FIELD_SIZE            6

/* end of Select_IF_Count_Type_Ref0*/


/* start of register Select_IF_Count_Type_Mask0*/

#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_QUEUE_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_PORT_FIELD_OFFSET         15
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_QUEUE_SEL_FIELD_OFFSET            21
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_PRIO_REQ_FIELD_OFFSET         22
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_PRIO_RES_FIELD_OFFSET         23
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_NULL_ATTR_FIELD_OFFSET            24


#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_QUEUE_FIELD_SIZE          15
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_PORT_FIELD_SIZE           6
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_QUEUE_SEL_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_PRIO_REQ_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_PRIO_RES_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_SELECT_IF_COUNT_TYPE_MASK0_SELECT_COUNT_MASK_REF_NULL_ATTR_FIELD_SIZE          6

/* end of Select_IF_Count_Type_Mask0*/


/* start of register pds2sdq_deq_if_cnt_lsb*/

#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_CNT_LSB_PDS2SDQ_DEQ_IF_CNT_LSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_CNT_LSB_PDS2SDQ_DEQ_IF_CNT_LSB_FIELD_SIZE           32

/* end of pds2sdq_deq_if_cnt_lsb*/


/* start of register PDS2SDQ_DEQ_IF_Count_Type_Ref*/

#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_CONT_REF_QUEUE_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_PORT_FIELD_OFFSET          15
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_DEQ_FIELD_OFFSET           21
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_DEQ_BC_FIELD_OFFSET            22
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_PRIO_FIELD_OFFSET          23
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_EMPTY_FIELD_OFFSET         24
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_NULL_ATTR_FIELD_OFFSET         25


#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_CONT_REF_QUEUE_FIELD_SIZE            15
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_PORT_FIELD_SIZE            6
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_DEQ_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_DEQ_BC_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_PRIO_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_EMPTY_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_REF_DEQ_COUNT_REF_NULL_ATTR_FIELD_SIZE           6

/* end of PDS2SDQ_DEQ_IF_Count_Type_Ref*/


/* start of register PDS2SDQ_DEQ_IF_Count_Type_Mask*/

#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_QUEUE_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_PORT_FIELD_OFFSET            15
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_DEQ_FIELD_OFFSET         21
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_DEQ_BC_FIELD_OFFSET          22
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_PRIO_FIELD_OFFSET            23
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_EMPTY_FIELD_OFFSET           24
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_NULL_ATTR_FIELD_OFFSET           25


#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_QUEUE_FIELD_SIZE         15
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_PORT_FIELD_SIZE          6
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_DEQ_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_DEQ_BC_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_PRIO_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_EMPTY_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_COUNT_TYPE_MASK_DEQ_COUNT_MASK_REF_NULL_ATTR_FIELD_SIZE         6

/* end of PDS2SDQ_DEQ_IF_Count_Type_Mask*/


/* start of register pds2sdq_deq_if_cnt_msb*/

#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_CNT_MSB_PDS2SDQ_DEQ_IF_CNT_MSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PDS2SDQ_DEQ_IF_CNT_MSB_PDS2SDQ_DEQ_IF_CNT_MSB_FIELD_SIZE           32

/* end of pds2sdq_deq_if_cnt_msb*/


/* start of register pdq_sdq_if_cnt_lsb*/

#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_CNT_LSB_PDQ_SDQ_IF_CNT_LSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_CNT_LSB_PDQ_SDQ_IF_CNT_LSB_FIELD_SIZE           32

/* end of pdq_sdq_if_cnt_lsb*/


/* start of register PDQ_SDQ_IF_Count_Type_Ref*/

#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_QUEUE_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_PORT_FIELD_OFFSET          15
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_BP_TYPE_FIELD_OFFSET           21
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_CRDT_TYPE_FIELD_OFFSET         22
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_QCN_TYPE_FIELD_OFFSET          23
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_QDRYER_TYPE_FIELD_OFFSET           24


#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_QUEUE_FIELD_SIZE           15
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_PORT_FIELD_SIZE            6
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_BP_TYPE_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_CRDT_TYPE_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_QCN_TYPE_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_REF_PDQ_COUNT_REF_QDRYER_TYPE_FIELD_SIZE         1

/* end of PDQ_SDQ_IF_Count_Type_Ref*/


/* start of register PDQ_SDQ_IF_Count_Type_Mask*/

#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_QUEUE_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_PORT_FIELD_OFFSET            15
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_BP_TYPE_FIELD_OFFSET         21
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_CRDT_TYPE_FIELD_OFFSET           22
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_QCN_TYPE_FIELD_OFFSET            23
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_QDRYER_TYPE_FIELD_OFFSET         24


#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_QUEUE_FIELD_SIZE         15
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_PORT_FIELD_SIZE          6
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_BP_TYPE_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_CRDT_TYPE_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_QCN_TYPE_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_COUNT_TYPE_MASK_PDQ_COUNT_MASK_REF_QDRYER_TYPE_FIELD_SIZE           1

/* end of PDQ_SDQ_IF_Count_Type_Mask*/


/* start of register pdq_sdq_if_cnt_msb*/

#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_CNT_MSB_PDQ_SDQ_IF_CNT_MSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PDQ_SDQ_IF_CNT_MSB_PDQ_SDQ_IF_CNT_MSB_FIELD_SIZE           32

/* end of pdq_sdq_if_cnt_msb*/


/* start of register pds2sdq_enq_if_cnt_lsb*/

#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_CNT_LSB_PDS2SDQ_ENQ_IF_CNT_LSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_CNT_LSB_PDS2SDQ_ENQ_IF_CNT_LSB_FIELD_SIZE           32

/* end of pds2sdq_enq_if_cnt_lsb*/


/* start of register PDS2SDQ_ENQ_IF_Count_Type_Ref*/

#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_REF_ENQ_COUNT_REF_QUEUE_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_REF_ENQ_COUNT_REF_PORT_FIELD_OFFSET          15
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_REF_ENQ_COUNT_REF_PRIO_FIELD_OFFSET          21


#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_REF_ENQ_COUNT_REF_QUEUE_FIELD_SIZE           15
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_REF_ENQ_COUNT_REF_PORT_FIELD_SIZE            6
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_REF_ENQ_COUNT_REF_PRIO_FIELD_SIZE            1

/* end of PDS2SDQ_ENQ_IF_Count_Type_Ref*/


/* start of register PDS2SDQ_ENQ_IF_Count_Type_Mask*/

#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_MASK_ENQ_COUNT_MASK_QUEUE_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_MASK_ENQ_COUNT_MASK_PORT_FIELD_OFFSET            15
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_MASK_ENQ_COUNT_MASK_REF_PRIO_FIELD_OFFSET            21


#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_MASK_ENQ_COUNT_MASK_QUEUE_FIELD_SIZE         15
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_MASK_ENQ_COUNT_MASK_PORT_FIELD_SIZE          6
#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_COUNT_TYPE_MASK_ENQ_COUNT_MASK_REF_PRIO_FIELD_SIZE          1

/* end of PDS2SDQ_ENQ_IF_Count_Type_Mask*/


/* start of register pds2sdq_enq_if_cnt_msb*/

#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_CNT_MSB_PDS2SDQ_ENQ_IF_CNT_MSB_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PDS2SDQ_ENQ_IF_CNT_MSB_PDS2SDQ_ENQ_IF_CNT_MSB_FIELD_SIZE           32

/* end of pds2sdq_enq_if_cnt_msb*/


/* start of register QBV_Config*/

#define      TXQ_AAS_SDQ_QBV_CONFIG_PORT_QBV_EN_0_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_QBV_CONFIG_PORT_QBV_EN_0_FIELD_SIZE            1

/* end of QBV_Config*/


/* start of register Port_Egress_TOD_Offset*/

#define      TXQ_AAS_SDQ_PORT_EGRESS_TOD_OFFSET_PORT_EGRESS_TOD_OFFSET_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PORT_EGRESS_TOD_OFFSET_PORT_EGRESS_TOD_OFFSET_0_FIELD_SIZE         30

/* end of Port_Egress_TOD_Offset*/


/* start of register Port_TableSet_Cycle_Time*/

#define      TXQ_AAS_SDQ_PORT_TABLESET_CYCLE_TIME_PORT_TABLESET_CYC_TIME_0_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PORT_TABLESET_CYCLE_TIME_PORT_TABLESET_CYC_TIME_0_FIELD_SIZE           30

/* end of Port_TableSet_Cycle_Time*/


/* start of register Port_TableSet_Cycle_Start*/

#define      TXQ_AAS_SDQ_PORT_TABLESET_CYCLE_START_PORT_TABLESET_CYC_START_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PORT_TABLESET_CYCLE_START_PORT_TABLESET_CYC_START_0_FIELD_SIZE         32

/* end of Port_TableSet_Cycle_Start*/


/* start of register Port_Last_TOD_SEC*/

#define      TXQ_AAS_SDQ_PORT_LAST_TOD_SEC_PORT_LAST_TOD_SEC_0_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PORT_LAST_TOD_SEC_PORT_LAST_TOD_SEC_0_FIELD_SIZE           2

/* end of Port_Last_TOD_SEC*/


/* start of register Config_Change_Time_TOD_LSB*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_TOD_LSB_QBV_CHANGE_TIME_TOD_LSB_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_TOD_LSB_QBV_CHANGE_TIME_TOD_LSB_FIELD_SIZE          32

/* end of Config_Change_Time_TOD_LSB*/


/* start of register Port_QBV_TableSet*/

#define      TXQ_AAS_SDQ_PORT_QBV_TABLESET_TABLE_SET_INDEX_0_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_PORT_QBV_TABLESET_TABLE_SET_ENTRY_0_FIELD_OFFSET           4
#define      TXQ_AAS_SDQ_PORT_QBV_TABLESET_LAST_TBL_SET_ENTRY_0_FIELD_OFFSET            12


#define      TXQ_AAS_SDQ_PORT_QBV_TABLESET_TABLE_SET_INDEX_0_FIELD_SIZE         4
#define      TXQ_AAS_SDQ_PORT_QBV_TABLESET_TABLE_SET_ENTRY_0_FIELD_SIZE         8
#define      TXQ_AAS_SDQ_PORT_QBV_TABLESET_LAST_TBL_SET_ENTRY_0_FIELD_SIZE          8

/* end of Port_QBV_TableSet*/


/* start of register Config_Change_Time_TOD_MSB_Low*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_TOD_MSB_LOW_QBV_CHANGE_TIME_TOD_MSB_LOW_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_TOD_MSB_LOW_QBV_CHANGE_TIME_TOD_MSB_LOW_FIELD_SIZE          32

/* end of Config_Change_Time_TOD_MSB_Low*/


/* start of register Config_Change_Time_TOD_MSB_High*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_TOD_MSB_HIGH_QBV_CHANGE_TIME_TOD_MSB_HIGH_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_TOD_MSB_HIGH_QBV_CHANGE_TIME_TOD_MSB_HIGH_FIELD_SIZE            14

/* end of Config_Change_Time_TOD_MSB_High*/


/* start of register Config_Change_Time_Ext*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_EXT_QBV_CHANGE_TIME_EXT_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_EXT_QBV_CHANGE_TIME_EXT_FIELD_SIZE          16

/* end of Config_Change_Time_Ext*/


/* start of register Config_Change_Time_Req*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_TIME_PEND_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_PORT_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_TABLESET_FIELD_OFFSET            6
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_LAST_ENTRY_FIELD_OFFSET          10
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_LENGTH_AWR_EN__FIELD_OFFSET          18
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_REMAIN_PER_NS_FIELD_OFFSET           19


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_TIME_PEND_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_TABLESET_FIELD_SIZE          4
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_LAST_ENTRY_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_LENGTH_AWR_EN__FIELD_SIZE            1
#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_REQ_QBV_CHANGE_REMAIN_PER_NS_FIELD_SIZE         11

/* end of Config_Change_Time_Req*/


/* start of register Config_Change_Time_Cycle_Time*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_CYCLE_TIME_QBV_CHANGE_TIME_CYCLE_TIME_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_CYCLE_TIME_QBV_CHANGE_TIME_CYCLE_TIME_FIELD_SIZE            30

/* end of Config_Change_Time_Cycle_Time*/


/* start of register Config_Change_Time_Egress_TOD_Offset*/

#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_EGRESS_TOD_OFFSET_QBV_CHANGE_TIME_EGRESS_TOD_OFFSET_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_CONFIG_CHANGE_TIME_EGRESS_TOD_OFFSET_QBV_CHANGE_TIME_EGRESS_TOD_OFFSET_FIELD_SIZE          30

/* end of Config_Change_Time_Egress_TOD_Offset*/


/* start of register Debug_Cycle_Time_Sync_Port*/

#define      TXQ_AAS_SDQ_DEBUG_CYCLE_TIME_SYNC_PORT_DEBUG_CYCLE_TIME_SYNC_PORT_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_DEBUG_CYCLE_TIME_SYNC_PORT_DEBUG_CYCLE_TIME_SYNC_PORT_0_FIELD_SIZE         5

/* end of Debug_Cycle_Time_Sync_Port*/


/* start of register Debug_Cycle_Time_Sync_offset*/

#define      TXQ_AAS_SDQ_DEBUG_CYCLE_TIME_SYNC_OFFSET_DEBUG_CYCLE_TIME_SYNC_OFFSET_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_DEBUG_CYCLE_TIME_SYNC_OFFSET_DEBUG_CYCLE_TIME_SYNC_OFFSET_0_FIELD_SIZE         30

/* end of Debug_Cycle_Time_Sync_offset*/


/* start of register Debug_Cycle_Time_Sync_Duration*/

#define      TXQ_AAS_SDQ_DEBUG_CYCLE_TIME_SYNC_DURATION_DEBUG_CYCLE_TIME_SYNC_DURATION_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_DEBUG_CYCLE_TIME_SYNC_DURATION_DEBUG_CYCLE_TIME_SYNC_DURATION_0_FIELD_SIZE         30

/* end of Debug_Cycle_Time_Sync_Duration*/


/* start of register Port_Length_Awr_Attr*/

#define      TXQ_AAS_SDQ_PORT_LENGTH_AWR_ATTR_PORT_LENGTH_AWARE_EN_0_FIELD_OFFSET           0
#define      TXQ_AAS_SDQ_PORT_LENGTH_AWR_ATTR_PORT_REMAIN_PER_NS_0_FIELD_OFFSET         1


#define      TXQ_AAS_SDQ_PORT_LENGTH_AWR_ATTR_PORT_LENGTH_AWARE_EN_0_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_LENGTH_AWR_ATTR_PORT_REMAIN_PER_NS_0_FIELD_SIZE           11

/* end of Port_Length_Awr_Attr*/


/* start of register Port_Max_Alwd_BC_Offset*/

#define      TXQ_AAS_SDQ_PORT_MAX_ALWD_BC_OFFSET_PORT_MAX_ALWD_BC_OFFSET_0_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_PORT_MAX_ALWD_BC_OFFSET_PORT_MAX_ALWD_BC_OFFSET_0_FIELD_SIZE           14

/* end of Port_Max_Alwd_BC_Offset*/


/* start of register Port_Remain_Per_NS_Resolution*/

#define      TXQ_AAS_SDQ_PORT_REMAIN_PER_NS_RESOLUTION_PORT_REMAIN_PER_NS_RES_0_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_PORT_REMAIN_PER_NS_RESOLUTION_PORT_REMAIN_PER_NS_RES_0_FIELD_SIZE          16

/* end of Port_Remain_Per_NS_Resolution*/


/* start of register TOD_Nanosec*/

#define      TXQ_AAS_SDQ_TOD_NANOSEC_TOD_NANOSEC_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_TOD_NANOSEC_TOD_NANOSEC_FIELD_SIZE         30

/* end of TOD_Nanosec*/


/* start of register TOD_Sec*/

#define      TXQ_AAS_SDQ_TOD_SEC_TOD_SEC_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_TOD_SEC_TOD_SEC_FIELD_SIZE         2

/* end of TOD_Sec*/


/* start of register TOD_MSB_Low*/

#define      TXQ_AAS_SDQ_TOD_MSB_LOW_TOD_MSB_LOW_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_TOD_MSB_LOW_TOD_MSB_LOW_FIELD_SIZE         32

/* end of TOD_MSB_Low*/


/* start of register TOD_MSB_High*/

#define      TXQ_AAS_SDQ_TOD_MSB_HIGH_TOD_MSB_HIGH_FIELD_OFFSET         0


#define      TXQ_AAS_SDQ_TOD_MSB_HIGH_TOD_MSB_HIGH_FIELD_SIZE           14

/* end of TOD_MSB_High*/


/* start of register Profile_Queue_TC*/

#define      TXQ_AAS_SDQ_PROFILE_QUEUE_TC_QUEUE_TC_PROFILE_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PROFILE_QUEUE_TC_QUEUE_TC_PROFILE_0_FIELD_SIZE         4

/* end of Profile_Queue_TC*/


/* start of register Profile_Q_Semi_Elig_Threshold*/

#define      TXQ_AAS_SDQ_PROFILE_Q_SEMI_ELIG_THRESHOLD_SEMI_ELIG_TH_PROFILE_0_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_PROFILE_Q_SEMI_ELIG_THRESHOLD_SEMI_ELIG_TH_PROFILE_0_FIELD_SIZE            7

/* end of Profile_Q_Semi_Elig_Threshold*/


/* start of register Profile_QCN_Div_Factor*/

#define      TXQ_AAS_SDQ_PROFILE_QCN_DIV_FACTOR_QCN_DIV_FACTOR_PROFILE_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PROFILE_QCN_DIV_FACTOR_QCN_DIV_FACTOR_PROFILE_0_FIELD_SIZE         6

/* end of Profile_QCN_Div_Factor*/


/* start of register Profile_Queue_Prio*/

#define      TXQ_AAS_SDQ_PROFILE_QUEUE_PRIO_QUEUE_PRIO_PROFILE_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PROFILE_QUEUE_PRIO_QUEUE_PRIO_PROFILE_0_FIELD_SIZE         1

/* end of Profile_Queue_Prio*/


/* start of register profile_queue_gate*/

#define      TXQ_AAS_SDQ_PROFILE_QUEUE_GATE_QUEUE_GATE_PROFILE_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PROFILE_QUEUE_GATE_QUEUE_GATE_PROFILE_0_FIELD_SIZE         3

/* end of profile_queue_gate*/


/* start of register Profile_Queue_AVB_en*/

#define      TXQ_AAS_SDQ_PROFILE_QUEUE_AVB_EN_QUEUE_AVB_EN_PROFILE_0_FIELD_OFFSET           0


#define      TXQ_AAS_SDQ_PROFILE_QUEUE_AVB_EN_QUEUE_AVB_EN_PROFILE_0_FIELD_SIZE         1

/* end of Profile_Queue_AVB_en*/


/* start of register Profile_Q_Aging_Credit_Threshold*/

#define      TXQ_AAS_SDQ_PROFILE_Q_AGING_CREDIT_THRESHOLD_AGING_CRDT_TH_PROFILE_0_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_PROFILE_Q_AGING_CREDIT_THRESHOLD_AGING_CRDT_TH_PROFILE_0_FIELD_SIZE            16

/* end of Profile_Q_Aging_Credit_Threshold*/


/* start of register Profile_Q_High_Credit_Threshold*/

#define      TXQ_AAS_SDQ_PROFILE_Q_HIGH_CREDIT_THRESHOLD_HIGH_CRDT_TH_PROFILE_0_FIELD_OFFSET            0


#define      TXQ_AAS_SDQ_PROFILE_Q_HIGH_CREDIT_THRESHOLD_HIGH_CRDT_TH_PROFILE_0_FIELD_SIZE          11

/* end of Profile_Q_High_Credit_Threshold*/


/* start of register Profile_Q_Low_Credit_Threshold*/

#define      TXQ_AAS_SDQ_PROFILE_Q_LOW_CREDIT_THRESHOLD_LOW_CRDT_TH_PROFILE_0_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_PROFILE_Q_LOW_CREDIT_THRESHOLD_LOW_CRDT_TH_PROFILE_0_FIELD_SIZE            11

/* end of Profile_Q_Low_Credit_Threshold*/


/* start of register Profile_Q_Neg_Credit_Threshold*/

#define      TXQ_AAS_SDQ_PROFILE_Q_NEG_CREDIT_THRESHOLD_NEG_CRDT_TH_PROFILE_0_FIELD_OFFSET          0


#define      TXQ_AAS_SDQ_PROFILE_Q_NEG_CREDIT_THRESHOLD_NEG_CRDT_TH_PROFILE_0_FIELD_SIZE            11

/* end of Profile_Q_Neg_Credit_Threshold*/


/* start of table entry Queue_To_Profile_Map*/

#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_PROFILE_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_1_PROFILE_FIELD_OFFSET          8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_2_PROFILE_FIELD_OFFSET          16
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_3_PROFILE_FIELD_OFFSET          24
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_4_PROFILE_FIELD_OFFSET          32
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_5_PROFILE_FIELD_OFFSET          40
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_6_PROFILE_FIELD_OFFSET          48
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_7_PROFILE_FIELD_OFFSET          56


#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_PROFILE_FIELD_SIZE          8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_1_PROFILE_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_2_PROFILE_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_3_PROFILE_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_4_PROFILE_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_5_PROFILE_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_6_PROFILE_FIELD_SIZE            8
#define      TXQ_AAS_SDQ_QUEUE_TO_PROFILE_MAP_QUEUE_7_PROFILE_FIELD_SIZE            8

/* end of Queue_To_Profile_Map*/


/* start of table entry Queue_To_Port_Map*/

#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_PORT_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_1_PORT_FIELD_OFFSET            5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_2_PORT_FIELD_OFFSET            10
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_3_PORT_FIELD_OFFSET            15
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_4_PORT_FIELD_OFFSET            20
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_5_PORT_FIELD_OFFSET            25
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_6_PORT_FIELD_OFFSET            30
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_7_PORT_FIELD_OFFSET            35


#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_PORT_FIELD_SIZE            5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_1_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_2_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_3_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_4_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_5_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_6_PORT_FIELD_SIZE          5
#define      TXQ_AAS_SDQ_QUEUE_TO_PORT_MAP_QUEUE_7_PORT_FIELD_SIZE          5

/* end of Queue_To_Port_Map*/
/* start of table entry queue_crdt_blnc*/

#define      TXQ_AAS_SDQ_QUEUE_CRDT_BLNC_TSTMP_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_QUEUE_CRDT_BLNC_CRDT_BLNC_FIELD_OFFSET         16


#define      TXQ_AAS_SDQ_QUEUE_CRDT_BLNC_TSTMP_FIELD_SIZE           16
#define      TXQ_AAS_SDQ_QUEUE_CRDT_BLNC_CRDT_BLNC_FIELD_SIZE           19

/* end of queue_crdt_blnc*/


/* start of table entry queue_elig_state*/

#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_CRDT_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_QCN_FIELD_OFFSET          2
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_DRY_FIELD_OFFSET          3
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_INPORTCNT_FIELD_OFFSET            4
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_INSEL_FIELD_OFFSET            5
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_ENQ_FIELD_OFFSET          6
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_SELIG_FIELD_OFFSET            7
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_ELIG4SEL_FIELD_OFFSET         8
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_SELIG4DRY_FIELD_OFFSET            9
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_PFC_FIELD_OFFSET          10
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_QBV_FIELD_OFFSET          11


#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_CRDT_FIELD_SIZE           2
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_QCN_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_DRY_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_INPORTCNT_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_INSEL_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_ENQ_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_SELIG_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_ELIG4SEL_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_SELIG4DRY_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_PFC_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_QUEUE_ELIG_STATE_QBV_FIELD_SIZE            1

/* end of queue_elig_state*/


/* start of table entry port_crdt_blnc*/

#define      TXQ_AAS_SDQ_PORT_CRDT_BLNC_PORT_QCNT_FIELD_OFFSET          0
#define      TXQ_AAS_SDQ_PORT_CRDT_BLNC_PORT_BLNC_FIELD_OFFSET          13


#define      TXQ_AAS_SDQ_PORT_CRDT_BLNC_PORT_QCNT_FIELD_SIZE            13
#define      TXQ_AAS_SDQ_PORT_CRDT_BLNC_PORT_BLNC_FIELD_SIZE            31

/* end of port_crdt_blnc*/


/* start of table entry port_pfc_state*/

#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC0_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC1_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC2_FIELD_OFFSET            2
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC3_FIELD_OFFSET            3
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC4_FIELD_OFFSET            4
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC5_FIELD_OFFSET            5
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC6_FIELD_OFFSET            6
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC7_FIELD_OFFSET            7
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC8_FIELD_OFFSET            8
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC9_FIELD_OFFSET            9
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC10_FIELD_OFFSET           10
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC11_FIELD_OFFSET           11
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC12_FIELD_OFFSET           12
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC13_FIELD_OFFSET           13
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC14_FIELD_OFFSET           14
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC15_FIELD_OFFSET           15


#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC0_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC1_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC2_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC3_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC4_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC5_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC6_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC7_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC8_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC9_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC10_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC11_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC12_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC13_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC14_FIELD_SIZE         1
#define      TXQ_AAS_SDQ_PORT_PFC_STATE_TC15_FIELD_SIZE         1

/* end of port_pfc_state*/


/* start of table entry port_qbv_state*/

#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT0_FIELD_OFFSET            0
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT1_FIELD_OFFSET            1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT2_FIELD_OFFSET            2
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT3_FIELD_OFFSET            3
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT4_FIELD_OFFSET            4
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT5_FIELD_OFFSET            5
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT6_FIELD_OFFSET            6
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT7_FIELD_OFFSET            7
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_HLD_RLS_FIELD_OFFSET            8


#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT0_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT1_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT2_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT3_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT4_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT5_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT6_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_GT7_FIELD_SIZE          1
#define      TXQ_AAS_SDQ_PORT_QBV_STATE_HLD_RLS_FIELD_SIZE          1

/* end of port_qbv_state*/


/* start of table entry qbv_cfg*/

#define      TXQ_AAS_SDQ_QBV_CFG_HOLD_RELEASE_NEXT_FIELD_OFFSET         0
#define      TXQ_AAS_SDQ_QBV_CFG_HOLD_RELEASE_CURRENT_FIELD_OFFSET          1
#define      TXQ_AAS_SDQ_QBV_CFG_GATE_STATE_NEXT_FIELD_OFFSET           2
#define      TXQ_AAS_SDQ_QBV_CFG_GATE_STATE_CURRENT_FIELD_OFFSET            10
#define      TXQ_AAS_SDQ_QBV_CFG_TIME_TO_ADVANCE_FIELD_OFFSET           18


#define      TXQ_AAS_SDQ_QBV_CFG_HOLD_RELEASE_NEXT_FIELD_SIZE           1
#define      TXQ_AAS_SDQ_QBV_CFG_HOLD_RELEASE_CURRENT_FIELD_SIZE            1
#define      TXQ_AAS_SDQ_QBV_CFG_GATE_STATE_NEXT_FIELD_SIZE         8
#define      TXQ_AAS_SDQ_QBV_CFG_GATE_STATE_CURRENT_FIELD_SIZE          8
#define      TXQ_AAS_SDQ_QBV_CFG_TIME_TO_ADVANCE_FIELD_SIZE         32

/* end of qbv_cfg*/


#endif
