#!/bin/sh
#ARG1:slot_name

sleep 1;
	echo ">>> act-pkg argc : ${#}, argv : ${@}";

SWM_INVENTORY_PATH="/fhm/system/pkg/"
SWM_INVENTORY_ACTIVE_FILE="ACTIVE"
SWM_BOOT_PATH="/mnt/flash/boot/"

if [ $# != 1 ]; then
	logger -p err [$1]SWM_ACTIVATION_APPLICATION_ERROR;
	/sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $1;
	exit 1; 
fi

case $1 in
slot0)
	;;
slot1)
	;;
*)
	logger -p err [$1] SWM_ACTIVATION_APPLICATION_ERROR;
	/sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $1;
	exit 1; 
	;;
esac

find ${SWM_INVENTORY_PATH} -mindepth 2 -maxdepth 2 | grep ${SWM_INVENTORY_ACTIVE_FILE} | xargs rm -f;
touch ${SWM_INVENTORY_PATH}/$1/${SWM_INVENTORY_ACTIVE_FILE};
if [ $? != 0 ]; then 
logger -p err [$1] SWM_ACTIVATION_APPLICATION_ERROR;
/sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $1; 
exit 1; fi;

IMAGE_NAME=`ls /fhm/system/pkg/$1/ | grep fhm-ociu- | grep bin | awk 'NR==1{print $1}'`
rm -rf ${SWM_BOOT_PATH}/*;
cp -f ${SWM_INVENTORY_PATH}/$1/${IMAGE_NAME}  ${SWM_BOOT_PATH};
sleep 0.5;
cd ${SWM_BOOT_PATH}

ln -s ${IMAGE_NAME} uImage;

#/* [#18] 18-sw-download-activate-rpc-nand : kieun07, 2022.06.21 */

flag=$(fw_printenv bootcmd|awk '{print $2}')
if [ $flag != "boot_nand" ]; then
fw_setenv bootcmd "run boot_nand"
fi

#/* [#18] */

sync;
sleep 0.5;

logger -p info [$1] SWM_ACTIVATION_COMPLETED;
/sbin/sysd-util -m "SWM_ACTIVATION_COMPLETED" -a $1;

