#!/bin/sh
#ARG1:slot_name
#ARG2:cell_num
sleep 1;
    echo ">>> act-pkg argc : ${#}, argv : ${@}";
logger -p daemon.info SWM_ACTIVE_START [ OCIU ];

SWM_INVENTORY_PATH="/fhm/system/pkg/"
SWM_INVENTORY_ACTIVE_FILE="ACTIVE"
SWM_BOOT_PATH="/mnt/flash/boot/"
OCIU_ACTIVE_FAIL_FILE="/tmp/ociu_active_fail"
if [ $# != 2 ]; then
    logger -p err [$1]SWM_ACTIVATION_APPLICATION_ERROR : [ Wrong parameter ];
    touch ${OCIU_ACTIVE_FAIL_FILE};	
    /sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $2 -s $1 -d "Wrong parameter";
    exit 1;
fi

case $1 in
slot0)
    ;;
slot1)
    ;;
*)
    logger -p daemon.err [$1] SWM_ACTIVATION_APPLICATION_ERROR : [ Wrong slot parameter ];
    touch ${OCIU_ACTIVE_FAIL_FILE};
    /sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $2 -s $1 -d "Wrong slot parameter";
    exit 1;
    ;;
esac

find ${SWM_INVENTORY_PATH} -mindepth 2 -maxdepth 2 | grep ${SWM_INVENTORY_ACTIVE_FILE} | xargs rm -f;
touch ${SWM_INVENTORY_PATH}/$1/${SWM_INVENTORY_ACTIVE_FILE};
if [ $? != 0 ]; then
logger -p daemon.err [$1] SWM_ACTIVATION_APPLICATION_ERROR : [ Failed to make active file ];
touch ${OCIU_ACTIVE_FAIL_FILE};
/sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $2 -s $1 -d "Failed to make active file";
exit 1; fi;

IMAGE_NAME=`ls /fhm/system/pkg/$1/ | grep fhm-ociu- | grep bin | awk 'NR==1{print $1}'`
rm -rf ${SWM_BOOT_PATH}/*;
cp -f ${SWM_INVENTORY_PATH}/$1/${IMAGE_NAME}  ${SWM_BOOT_PATH};
sleep 0.5;
cd ${SWM_BOOT_PATH}

ln -s ${IMAGE_NAME} uImage;

# /* [#384] m-plane-software-update-notification : kieun07, 2022.12.22*/
if [ $? != 0 ]; then
    logger -p daemon.err [$1]SWM_ACTIVATION_APPLICATION_ERROR : [ OCIU IMG link fail ];
    touch ${OCIU_ACTIVE_FAIL_FILE};
    /sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $2 -s $1 -d "OCIU IMG link fail";
    exit 1;
fi
#/* [#384] */

#/* [#18] 18-sw-download-activate-rpc-nand : kieun07, 2022.06.21 */

flag=$(fw_printenv bootcmd|awk '{print $2}')
if [ $flag != "boot_nand" ]; then
fw_setenv bootcmd "run boot_nand"
fi

#/* [#18] */

# /* [#384] m-plane-software-update-notification : kieun07, 2022.12.22*/
if [ $? != 0 ]; then
    logger -p daemon.err [$1]SWM_ACTIVATION_APPLICATION_ERROR : [ Failed to change nand boot ];
    touch ${OCIU_ACTIVE_FAIL_FILE};
    /sbin/sysd-util -m "SWM_ACTIVATION_APPLICATION_ERROR" -a $2 -s $1 -d "Failed to change nand boot";
    exit 1;
fi
#/* [#384] */

sync;
sleep 0.5;

rm -rf ${OCIU_ACTIVE_FAIL_FILE};
logger -p daemon.info [$1] SWM_ACTIVATION_COMPLETED [ OCIU ];
/sbin/sysd-util -m "SWM_OCIU_ACTIVATION_COMPLETED" -a $2 -s $1;
