#!/bin/sh
# ARG1: ip_address
# ARG2: user
# ARG3: password
# ARG4: SFTP_PORT
# ARG5: filepath/filename

sleep 1;
echo ">>> conf-backup argc : ${#}, argv : ${@}";
logger -p daemon.info SFTP_CONF_BACKUP_START;

FHM_CONF_FILE_PATH="/mnt/flash/conf/FHM.conf"

if [ ${#} != 5 ]; then
    logger -p daemon.err CONF_BACKUP_ERROR : [ WRONG PARAMETER ];
    echo 1 > /tmp/.config_backup_restore_fail;
    exit 1;
fi

ssh-keygen -R $1;

logger -p daemon.info execute sftpput.exp;
/usr/bin/expect -f /sbin/sftpput.exp $2 $3 $1 ${FHM_CONF_FILE_PATH} $5 $4;
ERROR_CHECK="$?"

if [ ${ERROR_CHECK} != 0 ]; then
    logger -p daemon.err CONF_BACKUP_ERROR : [ERROR NUM : ${ERROR_CHECK}];
    echo ${ERROR_CHECK} > /tmp/.config_backup_restore_fail;
    exit 1;
fi

echo 0 > /tmp/.config_backup_restore_fail;
logger -p daemon.info CONF_BACKUP_COMPLETE;
