#!/bin/sh
# ARG1:netconfpid
# ARG2:netconf2pid

sleep 1;
#echo ">>> restart-netconf argc : ${#}, argv : ${@}";
logger -p daemon.info TRY_NETCONF_RESTART;

NETCONF1SOCK=/tmp/ncxserver830.sock
NETCONF2SOCK=/tmp/ncxserver840.sock
DAEMON=/usr/local/sbin/netconfd

if [ $1 == 0 ]; then
	find ${NETCONF1SOCK} > /dev/null 2>&1;
	if [ $? == 0 ]; then
    	rm -rf ${NETCONF1SOCK};
	fi

	find ${NETCONF2SOCK} > /dev/null 2>&1;
	if [ $? == 0 ]; then
    	rm -rf ${NETCONF2SOCK};
	fi

	/usr/local/sbin/netconfd --config=/usr/local/etc/yuma/netconfd-fhm.conf --ncxserver-sockname=/tmp/ncxserver830.sock --port=830 1> /dev/null &
	/usr/local/sbin/netconfd --config=/usr/local/etc/yuma/netconfd-fhm.conf --ncxserver-sockname=/tmp/ncxserver840.sock --port=840 1> /dev/null &
	logger -p daemon.info ALL_NETCONF_RESTART_COMPLETE;
fi


if [ $1 != 0 ] && [ $2 == 0 ]; then

	CELL=$(cat /proc/$1/cmdline |grep port= | cut -c 8-10 &)

	case ${CELL} in
	830)
		find ${NETCONF2SOCK} > /dev/null 2>&1;
		if [ $? == 0 ]; then
			rm -rf ${NETCONF2SOCK};
		fi
			/usr/local/sbin/netconfd --config=/usr/local/etc/yuma/netconfd-fhm.conf --ncxserver-sockname=/tmp/ncxserver840.sock --port=840 1> /dev/null &	
			logger -p daemon.info CELL2_NETCONF_RESTART_COMPLETE;
		;;
	840)
		find ${NETCONF1SOCK} > /dev/null 2>&1;
		if [ $? == 0 ]; then
			rm -rf ${NETCONF1SOCK};
		fi
			/usr/local/sbin/netconfd --config=/usr/local/etc/yuma/netconfd-fhm.conf --ncxserver-sockname=/tmp/ncxserver830.sock --port=830 1> /dev/null &
			logger -p daemon.info CELL1_NETCONF_RESTART_COMPLETE;
		;;
	*)
		logger -p daemon.err NETCONF_RESTART_WRONG_PORT_NUMBER;
		exit 1;
		;;
	esac
fi

exit 0;
