/*******************************************************************************
*              (c), Copyright 2018, Marvell International Ltd.                 *
* THIS CODE IS A REFERENCE CODE FOR MARVELL SWITCH PRODUCTS.  IT IS PROVIDED   *
* "AS IS" WITH NO WARRANTIES, EXPRESSED, IMPLIED OR OTHERWISE, REGARDING ITS   *
* ACCURACY, COMPLETENESS OR PERFORMANCE.                                       *
* CUSTOMERS ARE FREE TO MODIFY IT AND USE IT ONLY IN THEIR PRODUCTION          *
* SOFTWARE RELEASES WITH MARVELL SWITCH CHIPSETS.                              *
*******************************************************************************/
/**
********************************************************************************
* @file WM-AC%.c
*
* @brief AC5 CAP main profiles
*
* @version   1
********************************************************************************
*/

#include <profiles/cpssAppPlatformProfile.h>
#include <profiles/cpssAppPlatformProfileDecl.h>

/**** AC5X full profile - 1 PP ****/
CPSS_CAP_PROFILE_START( WM_AC5_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_AC5_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5_PP_INFO, &WM_AC5_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5 )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5_all, "AC5 - External Cpu" )
CPSS_CAP_PROFILE_START( DB_AC5_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5_28SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &DB_AC5_INT_CPU_PP_INFO, &WM_AC5_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5 )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5_all, "AC5 - Internal Cpu" )
CPSS_CAP_PROFILE_START( DB_AC5_all_noPorts )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5_28SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &DB_AC5_INT_CPU_PP_INFO, &WM_AC5_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_INFO_NO_PORTS )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5 )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5_all_noPorts, "AC5 - Internal Cpu with no ports initialized" )
CPSS_CAP_PROFILE_START( DB_AC5_all_noPorts_externalCpu )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5_28SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5_PP_INFO, &WM_AC5_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_INFO_NO_PORTS )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5 )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5_all_noPorts_externalCpu, "AC5 - External Cpu with no ports initialized" )
CPSS_CAP_PROFILE_START( DB_AC5_all_externalCpu )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5_28SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5_PP_INFO, &WM_AC5_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5 )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5_all_externalCpu, "AC5 - External Cpu" )
