/*******************************************************************************
*              (c), Copyright 2023, Marvell International Ltd.                 *
* THIS CODE IS A REFERENCE CODE FOR MARVELL SWITCH PRODUCTS.  IT IS PROVIDED   *
* "AS IS" WITH NO WARRANTIES, EXPRESSED, IMPLIED OR OTHERWISE, REGARDING ITS   *
* ACCURACY, COMPLETENESS OR PERFORMANCE.                                       *
* CUSTOMERS ARE FREE TO MODIFY IT AND USE IT ONLY IN THEIR PRODUCTION          *
* SOFTWARE RELEASES WITH MARVELL SWITCH CHIPSETS.                              *
*******************************************************************************/
/**
********************************************************************************
* @file WM-Harrier.c
*
* @brief Harrier CAP main profiles
*
* @version   1
********************************************************************************
*/

#include <profiles/cpssAppPlatformProfile.h>
#include <profiles/cpssAppPlatformProfileDecl.h>

CPSS_CAP_PROFILE_START( WM_HARRIER_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_HARRIER_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_HARRIER_PP_INFO, &WM_HARRIER_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_HARRIER_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_HARRIER )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_HARRIER_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_HARRIER_all, "Harrier - External Cpu" )

CPSS_CAP_PROFILE_START( WM_HARRIER_all_noports )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_HARRIER_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_HARRIER_PP_INFO, &WM_HARRIER_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_HARRIER_INFO_NOPORTS )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_HARRIER )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_HARRIER_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_HARRIER_all_noports, "Harrier - External Cpu with no ports" )

CPSS_CAP_PROFILE_START( WM_HARRIER_RT)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_HARRIER_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_HARRIER )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_HARRIER_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_HARRIER_RT, "Harrier - runtime profile" )

CPSS_CAP_PROFILE_START( WM_HARRIER_Link)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &LINK_WM_HARRIER_INFO )
CPSS_CAP_PROFILE_END( WM_HARRIER_Link, "Harrier - Link profile" )

CPSS_CAP_PROFILE_START( WM_HARRIER_Rx)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RX_WM_HARRIER_INFO )
CPSS_CAP_PROFILE_END( WM_HARRIER_Rx, "Harrier - Rx profile" )

/* HARRIER - board profile */
CPSS_CAP_PROFILE_START( WM_HARRIER_board_only )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_HARRIER_BOARD_INFO )
CPSS_CAP_PROFILE_END( WM_HARRIER_board_only, "Harrier - Board only" )

/* HARRIER with one PP */
CPSS_CAP_PROFILE_START (WM_HARRIER_PP_only)
  CPSS_CAP_ADD_PP_PROFILE (&WM_HARRIER_PP_INFO, &WM_HARRIER_PP_MAP_INFO)
CPSS_CAP_PROFILE_END (WM_HARRIER_PP_only, "Harrier - PP only")

