typedef enum {
	SVC_FAULT_EVT_LINK_DOWN,
	SVC_FAULT_EVT_LINK_UP,
	SVC_FAULT_EVT_MAX
} SVC_FAULT_EVT;

typedef enum {
	SVC_FAULT_ST_INIT,
	SVC_FAULT_ST_LFRF_CHECK,
	SVC_FAULT_ST_LF,
	SVC_FAULT_ST_FWD_LF,
	SVC_FAULT_ST_RF,
	SVC_FAULT_ST_FWD_RF,
	SVC_FAULT_ST_CLR_LF,
	SVC_FAULT_ST_CLR_RF,
	SVC_FAULT_ST_NO_LFRF,
	SVC_FAULT_ST_MAX
} SVC_FAULT_ST; 

typedef SVC_FAULT_ST (*FAULT_ST_CB_FUNC) (uint16_t port);

typedef struct svc_fault_fsm {
	SVC_FAULT_ST state;
	SVC_FAULT_EVT evt;
	uint16_t retry_cnt;
	uint16_t fwdPortBmp;
	FAULT_ST_CB_FUNC cb[SVC_FAULT_ST_MAX];
} SVC_FAULT_FSM;

#define FAULT_CHECK_MAX 10
#if 0/*[#40] IPC source 정리, balkrow, 2024-06-11 */
#define EAG6L_PORT_MAX 9
#endif
#define EAG6L_WDM_PORT 50
