/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsIronmanSDWUnits.h
*
* @brief IronmanL SerDes register DB header file
*
* @version   1
********************************************************************************
*/

#ifndef __mvHwsIronmanSDWUnits_H
#define __mvHwsIronmanSDWUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    /* SDW common units */
  /*0*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_0_PU_IVREF_E,
  /*1*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_0_SIF_SEL_E,
  /*2*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_0_ASYNC_RESET_E,
  /*3*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_0_REFCLK_DIS_E,
  /*4*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_0_CID_REV_E,
  /*5*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_0_RESERVED_INPUT_E,
  /*6*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK0_DIV_E,
  /*7*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK1_DIV_E,
  /*8*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_SYNC_E0_MUX_SEL_E,
  /*9*/   IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_SYNC_E1_MUX_SEL_E,
  /*10*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_SYNC_E0_LANE_SEL_E,
  /*11*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_SYNC_E1_LANE_SEL_E,
  /*12*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK0_AUTO_MASK_EN_E,
  /*13*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK1_AUTO_MASK_EN_E,
  /*14*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK0_LOCAL_CLK_DISABLED_E,
  /*15*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK1_LOCAL_CLK_DISABLED_E,
  /*16*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK0_LOCAL_CLK_DIV_RESET__E,
  /*17*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_RCVRD_CLK1_LOCAL_CLK_DIV_RESET__E,
  /*18*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_TX_CLK_ON_RCVRD_CLK0_E,
  /*19*/  IRONMAN_SDW_COMMON_GENERAL_CONTROL_1_TX_CLK_ON_RCVRD_CLK1_E,
  /*20*/  IRONMAN_SDW_COMMON_GENERAL_MUX_CONTROL_PU_IVREF_SELECT_E,
  /*21*/  IRONMAN_SDW_COMMON_GENERAL_MUX_CONTROL_ASYNC_RESET_SELECT_E,
  /*22*/  IRONMAN_SDW_COMMON_GENERAL_MUX_CONTROL_CID_REV_SELECT_E,
  /*23*/  IRONMAN_SDW_COMMON_GENERAL_MUX_CONTROL_RESERVED_INPUT_SELECT_E,
  /*24*/  IRONMAN_SDW_COMMON_WATCHDOG_TIMER_CONTROL_WATCHDOG_TIMER_VALUE_E,
  /*25*/  IRONMAN_SDW_COMMON_WATCHDOG_TIMER_CONTROL_WATCHDOG_TIMER_ENABLE_E,
  /*26*/  IRONMAN_SDW_COMMON_SDW_METAL_FIX_REGISTER_METALFIXBITS_E,
  /*27*/  IRONMAN_SDW_COMMON_GENERAL_STATUS_0_RESERVED_OUTPUT_E,
  /*28*/  IRONMAN_SDW_COMMON_GENERAL_STATUS_0_REFCLK_DIS_ACK_E,
  /*29*/  IRONMAN_SDW_COMMON_INTERRUPT_CAUSE_SUMMARY_E,
  /*30*/  IRONMAN_SDW_COMMON_INTERRUPT_CAUSE_SERDES_INTERRUPT_E,
  /*31*/  IRONMAN_SDW_COMMON_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_E,
  /*32*/  IRONMAN_SDW_COMMON_INTERRUPT_CAUSE_SQ_DETECT_0_E,
  /*33*/  IRONMAN_SDW_COMMON_INTERRUPT_MASK_INTERRUPT_MASK_E,
  /*34*/  IRONMAN_SDW_COMMON_INVALID_ADDRESS_LATCH_INVALID_ADDR_LATCH_E,

    /* SDW lane units */
  /*35*/  IRONMAN_SDW_LANE_CONTROL_0_PU_PLL_E,
  /*36*/  IRONMAN_SDW_LANE_CONTROL_0_PU_RX_E,
  /*37*/  IRONMAN_SDW_LANE_CONTROL_0_PU_TX_E,
  /*38*/  IRONMAN_SDW_LANE_CONTROL_0_PHY_GEN_RX_E,
  /*39*/  IRONMAN_SDW_LANE_CONTROL_0_PHY_GEN_TX_E,
  /*40*/  IRONMAN_SDW_LANE_CONTROL_0_TX_IDLE_E,
  /*41*/  IRONMAN_SDW_LANE_CONTROL_0_RX_INIT_E,
  /*42*/  IRONMAN_SDW_LANE_CONTROL_0_REF_FREF_SEL_E,
  /*43*/  IRONMAN_SDW_LANE_CONTROL_0_DFE_UPDATE_DIS_E,
  /*44*/  IRONMAN_SDW_LANE_CONTROL_0_DFE_PAT_DIS_E,
  /*45*/  IRONMAN_SDW_LANE_CONTROL_0_DFE_EN_E,
  /*46*/  IRONMAN_SDW_LANE_CONTROL_0_BACKCHANNEL_WINDOW_E,
  /*47*/  IRONMAN_SDW_LANE_CONTROL_0_SQ_DETECT_MASK_E,
  /*48*/  IRONMAN_SDW_LANE_CONTROL_0_SQ_DETECT_ACTIVE_LOW_E,
  /*49*/  IRONMAN_SDW_LANE_CONTROL_0_SW_RESET_TO_PCS_MASK_E,
  /*50*/  IRONMAN_SDW_LANE_CONTROL_0_REFCLK_SEL_E,
  /*51*/  IRONMAN_SDW_LANE_CONTROL_0_RX_DC_TERM_EN_E,
  /*52*/  IRONMAN_SDW_LANE_CONTROL_1_SSC_EN_E,
  /*53*/  IRONMAN_SDW_LANE_CONTROL_1_SYNC_DET_EN_E,
  /*54*/  IRONMAN_SDW_LANE_CONTROL_1_RESET_CORE_E,
  /*55*/  IRONMAN_SDW_LANE_CONTROL_1_RF_RESET_IN_E,
  /*56*/  IRONMAN_SDW_LANE_CONTROL_1_TXCLK_SYNC_EN_PLL_IN_E,
  /*57*/  IRONMAN_SDW_LANE_CONTROL_1_RX_TRAIN_ENABLE_E,
  /*58*/  IRONMAN_SDW_LANE_CONTROL_1_TX_TRAIN_ENABLE_E,
  /*59*/  IRONMAN_SDW_LANE_CONTROL_1_TX_TRAIN_FRAME_LOCK_ENABLE_E,
  /*60*/  IRONMAN_SDW_LANE_CONTROL_1_LOCAL_CTRL_FIELD_READY_E,
  /*61*/  IRONMAN_SDW_LANE_CONTROL_1_TXDATA_SAMP_SEL_E,
  /*62*/  IRONMAN_SDW_LANE_CONTROL_1_RXDATA_SAMP_SEL_E,
  /*63*/  IRONMAN_SDW_LANE_CONTROL_1_RX_NEGEDGE_SAMPLE_EN_E,
  /*64*/  IRONMAN_SDW_LANE_CONTROL_1_RX_CLK_ENABLE_E,
  /*65*/  IRONMAN_SDW_LANE_CONTROL_1_TX_CLK_ENABLE_E,
  /*66*/  IRONMAN_SDW_LANE_CONTROL_1_RX_CLK_4X_ENABLE_E,
  /*67*/  IRONMAN_SDW_LANE_CONTROL_1_TX_CLK_4X_ENABLE_E,
  /*68*/  IRONMAN_SDW_LANE_CONTROL_2_REMOTE_STATUS_FIELD_VALID_E,
  /*69*/  IRONMAN_SDW_LANE_CONTROL_2_REMOTE_STATUS_FIELD_E,
  /*70*/  IRONMAN_SDW_LANE_CONTROL_2_REMOTE_CTRL_FIELD_VALID_E,
  /*71*/  IRONMAN_SDW_LANE_CONTROL_2_REMOTE_CTRL_FIELD_E,
  /*72*/  IRONMAN_SDW_LANE_CONTROL_2_REMOTE_CTRL_FIELD_RESET_E,
  /*73*/  IRONMAN_SDW_LANE_CONTROL_3_RESERVED_INPUT_TX_E,
  /*74*/  IRONMAN_SDW_LANE_CONTROL_3_RESERVED_INPUT_RX_E,
  /*75*/  IRONMAN_SDW_LANE_MUX_CONTROL_PU_PLL_SELECT_E,
  /*76*/  IRONMAN_SDW_LANE_MUX_CONTROL_PU_RX_SELECT_E,
  /*77*/  IRONMAN_SDW_LANE_MUX_CONTROL_PU_TX_SELECT_E,
  /*78*/  IRONMAN_SDW_LANE_MUX_CONTROL_PHY_GEN_RX_SELECT_E,
  /*79*/  IRONMAN_SDW_LANE_MUX_CONTROL_PHY_GEN_TX_SELECT_E,
  /*80*/  IRONMAN_SDW_LANE_MUX_CONTROL_RX_INIT_SELECT_E,
  /*81*/  IRONMAN_SDW_LANE_MUX_CONTROL_TX_IDLE_SELECT_E,
  /*82*/  IRONMAN_SDW_LANE_MUX_CONTROL_COUPLE_MODE_EN_SELECT_E,
  /*83*/  IRONMAN_SDW_LANE_MUX_CONTROL_TXCLK_SYNC_EN_PLL_IN_SELECT_E,
  /*84*/  IRONMAN_SDW_LANE_MUX_CONTROL_RX_TRAIN_ENABLE_SELECT_E,
  /*85*/  IRONMAN_SDW_LANE_MUX_CONTROL_TX_TRAIN_ENABLE_SELECT_E,
  /*86*/  IRONMAN_SDW_LANE_MUX_CONTROL_RESET_CORE_SELECT_E,
  /*87*/  IRONMAN_SDW_LANE_MUX_CONTROL_RESERVED_INPUT_RX_SELECT_E,
  /*88*/  IRONMAN_SDW_LANE_MUX_CONTROL_RESERVED_INPUT_TX_SELECT_E,
  /*89*/  IRONMAN_SDW_LANE_MUX_CONTROL_RESERVE_ANP_IN_RX_SELECT_E,
  /*90*/  IRONMAN_SDW_LANE_MUX_CONTROL_RESERVE_ANP_IN_TX_SELECT_E,
  /*91*/  IRONMAN_SDW_LANE_MUX_CONTROL_DFE_EN_SELECT_E,
  /*92*/  IRONMAN_SDW_LANE_MUX_CONTROL_DFE_PAT_DIS_SELECT_E,
  /*93*/  IRONMAN_SDW_LANE_MUX_CONTROL_DFE_UPDATE_DIS_SELECT_E,
  /*94*/  IRONMAN_SDW_LANE_FIX_REGISTER_PRBS_PATTERN_ENABLE_E,
  /*95*/  IRONMAN_SDW_LANE_STATUS_0_SYNC_FOUND_E,
  /*96*/  IRONMAN_SDW_LANE_STATUS_0_SQ_DETECTED_E,
  /*97*/  IRONMAN_SDW_LANE_STATUS_0_PLL_READY_TX_E,
  /*98*/  IRONMAN_SDW_LANE_STATUS_0_PLL_READY_RX_E,
  /*99*/  IRONMAN_SDW_LANE_STATUS_0_RX_INIT_DONE_E,
  /*100*/ IRONMAN_SDW_LANE_STATUS_0_REALIGN_SYNC_FOUND_E,
  /*101*/ IRONMAN_SDW_LANE_STATUS_0_SQ_DETECTED_LPF_E,
  /*102*/ IRONMAN_SDW_LANE_STATUS_0_CDR_LOCK_E,
  /*103*/ IRONMAN_SDW_LANE_STATUS_0_TXCLK_SYNC_START_OUT_E,
  /*104*/ IRONMAN_SDW_LANE_STATUS_0_RX_TRAIN_COMPLETE_E,
  /*105*/ IRONMAN_SDW_LANE_STATUS_0_RX_TRAIN_FAILED_E,
  /*106*/ IRONMAN_SDW_LANE_STATUS_0_TX_TRAIN_COMPLETE_E,
  /*107*/ IRONMAN_SDW_LANE_STATUS_0_TX_TRAIN_FAILED_E,
  /*108*/ IRONMAN_SDW_LANE_STATUS_0_TX_TRAIN_FRAME_LOCK_DETECTED_E,
  /*109*/ IRONMAN_SDW_LANE_STATUS_0_TX_TRAIN_ERROR_E,
  /*110*/ IRONMAN_SDW_LANE_STATUS_1_REMOTE_CTRL_FIELD_READY_E,
  /*111*/ IRONMAN_SDW_LANE_STATUS_1_LOCAL_STATUS_FIELD_VALID_E,
  /*112*/ IRONMAN_SDW_LANE_STATUS_1_LOCAL_STATUS_FIELD_E,
  /*113*/ IRONMAN_SDW_LANE_STATUS_1_LOCAL_CTRL_FIELD_VALID_E,
  /*114*/ IRONMAN_SDW_LANE_STATUS_1_LOCAL_CTRL_FIELD_RESET_E,
  /*115*/ IRONMAN_SDW_LANE_STATUS_1_LOCAL_CTRL_FIELD_E,
  /*116*/ IRONMAN_SDW_LANE_STATUS_2_RESERVED_OUTPUT_TX_E,
  /*117*/ IRONMAN_SDW_LANE_STATUS_2_RESERVED_OUTPUT_RX_E,
    IRONMAN_SDW_LANE_REGISTER_LAST_E /* should be last */
} MV_HWS_IRONMAN_SDW_UNIT_E;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsIronmanSDWUnits_H */


