/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,     *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*
* prvCpssAasTxqPdxRegFile.h
*
*Automaticly generated from :
*
* DESCRIPTION:
*      Describe TXQ PDX registers (Automaticly generated from CIDER)
*
* DEPENDENCIES:
*       None.
*
* FILE REVISION NUMBER:
*       $Revision: 1 $
*
*******************************************************************************/
#ifndef _TXQ_AAS__PDX_REGFILE_H_
#define _TXQ_AAS__PDX_REGFILE_H_

/* start of register pdx_metal_fix*/

#define      TXQ_AAS_PDX_PDX_METAL_FIX_PDX_METAL_FIX_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_PDX_METAL_FIX_PDX_METAL_FIX_FIELD_SIZE         32

/* end of pdx_metal_fix*/


/* start of register DB_Read_Control*/

#define      TXQ_AAS_PDX_DB_READ_CONTROL_DB_READ_CONTROL_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_DB_READ_CONTROL_DB_READ_CONTROL_FIELD_SIZE         11

/* end of DB_Read_Control*/


/* start of register QCX_Read_qu_db*/

#define      TXQ_AAS_PDX_QCX_READ_QU_DB_QCX_READ_QU_DB_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_QCX_READ_QU_DB_QCX_READ_QU_DB_FIELD_SIZE           20

/* end of QCX_Read_qu_db*/


/* start of register QCX_Read_Port_DB*/

#define      TXQ_AAS_PDX_QCX_READ_PORT_DB_QCX_READ_PORT_DB_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_QCX_READ_PORT_DB_QCX_READ_PORT_DB_FIELD_SIZE           20

/* end of QCX_Read_Port_DB*/


/* start of register QCX_Read_Reorder_Fifos*/

#define      TXQ_AAS_PDX_QCX_READ_REORDER_FIFOS_QCX_READ_REORDER_FIFOS_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_QCX_READ_REORDER_FIFOS_QCX_READ_REORDER_FIFOS_FIELD_SIZE           30

/* end of QCX_Read_Reorder_Fifos*/


/* start of register QCX_Wrong_Qgrpmap_Addr*/

#define      TXQ_AAS_PDX_QCX_WRONG_TRG_PORT_MAP_ADDR_QCX_WRONG_LOCAL_DEV_TRG_PHY_PORT_FIELD_OFFSET			0


#define      TXQ_AAS_PDX_QCX_WRONG_TRG_PORT_MAP_ADDR_QCX_WRONG_LOCAL_DEV_TRG_PHY_PORT_FIELD_SIZE			10

/* end of QCX_Wrong_Qgrpmap_Addr*/


/* start of register QCX_Wrong_PDS_Target*/

#define      TXQ_AAS_PDX_QCX_WRONG_PDS_TARGET_QCX_WRONG_PDS_TRGT_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_QCX_WRONG_PDS_TARGET_QCX_WRONG_PDS_TRGT_FIELD_SIZE         3

/* end of QCX_Wrong_PDS_Target*/


/* start of register QCX_Wrong_Port_Target*/

#define      TXQ_AAS_PDX_QCX_WRONG_PORT_TARGET_QCX_WRONG_PORT_TRGT_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_QCX_WRONG_PORT_TARGET_QCX_WRONG_PORT_TRGT_FIELD_SIZE           6

/* end of QCX_Wrong_Port_Target*/


/* start of register dp_core_mapping_register_pds_id*/

#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_PDS_ID_FIELD_OFFSET			0
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_1_PDS_ID_FIELD_OFFSET			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_2_PDS_ID_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_3_PDS_ID_FIELD_OFFSET			9
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_4_PDS_ID_FIELD_OFFSET			12
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_5_PDS_ID_FIELD_OFFSET			15
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_6_PDS_ID_FIELD_OFFSET			18
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_7_PDS_ID_FIELD_OFFSET			21


#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_1_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_2_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_3_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_4_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_5_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_6_PDS_ID_FIELD_SIZE			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDS_ID_DP_CORE_7_PDS_ID_FIELD_SIZE			3

/* end of dp_core_mapping_register_pds_id*/


/* start of register dp_core_mapping_register_pdx_id*/

#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_PDX_ID_FIELD_OFFSET			0
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_1_PDX_ID_FIELD_OFFSET			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_2_PDX_ID_FIELD_OFFSET			2
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_3_PDX_ID_FIELD_OFFSET			3
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_4_PDX_ID_FIELD_OFFSET			4
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_5_PDX_ID_FIELD_OFFSET			5
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_6_PDX_ID_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_7_PDX_ID_FIELD_OFFSET			7


#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_1_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_2_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_3_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_4_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_5_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_6_PDX_ID_FIELD_SIZE			1
#define      TXQ_AAS_PDX_DP_CORE_MAPPING_REGISTER_PDX_ID_DP_CORE_7_PDX_ID_FIELD_SIZE			1

/* end of dp_core_mapping_register_pdx_id*/


/* start of register CP_RXs_outstanding*/

#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX0_OUTSTANDING_FIELD_OFFSET            0
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX1_OUTSTANDING_FIELD_OFFSET            6
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX2_OUTSTANDING_FIELD_OFFSET            12
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX3_OUTSTANDING_FIELD_OFFSET            18
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX4_OUTSTANDING_FIELD_OFFSET            24


#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX0_OUTSTANDING_FIELD_SIZE          6
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX1_OUTSTANDING_FIELD_SIZE          6
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX2_OUTSTANDING_FIELD_SIZE          6
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX3_OUTSTANDING_FIELD_SIZE          6
#define      TXQ_AAS_PDX_CP_RXS_OUTSTANDING_RX4_OUTSTANDING_FIELD_SIZE          6

/* end of CP_RXs_outstanding*/



/* start of register PDX_dbg_Interrupt_Cause*/

#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_PDX_DBG_INTSUM_FIELD_OFFSET			0
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_WRONGLY_MAPPED_PORTMAP_DROP_INT_FIELD_OFFSET			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_WRONG_PORTMAP_ADDR_CP0_INT_FIELD_OFFSET			2
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_WRONG_PDS_TRGT_CP0_INT_FIELD_OFFSET			4
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_WRONG_PORT_TRGT_CP0_INT_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_ADDR_INT_FIELD_OFFSET			8
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_1_ADDR_INT_FIELD_OFFSET			9
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_2_ADDR_INT_FIELD_OFFSET			10
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_3_ADDR_INT_FIELD_OFFSET			11
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_4_ADDR_INT_FIELD_OFFSET			12
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_INT_FIELD_OFFSET			16
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_1_INT_FIELD_OFFSET			17
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_2_INT_FIELD_OFFSET			18
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_3_INT_FIELD_OFFSET			19
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_4_INT_FIELD_OFFSET			20
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_INT_FIELD_OFFSET			24
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_1_INT_FIELD_OFFSET			25
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_2_INT_FIELD_OFFSET			26
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_3_INT_FIELD_OFFSET			27
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_4_INT_FIELD_OFFSET			28
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_UNEXPECTED_QUEUE_INT_FIELD_OFFSET			29
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_UNEXPECTED_QUEUE_1_INT_FIELD_OFFSET			30


#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_PDX_DBG_INTSUM_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_WRONGLY_MAPPED_PORTMAP_DROP_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_WRONG_PORTMAP_ADDR_CP0_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_WRONG_PDS_TRGT_CP0_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_WRONG_PORT_TRGT_CP0_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_ADDR_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_1_ADDR_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_2_ADDR_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_3_ADDR_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORTMAP_4_ADDR_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_1_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_2_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_3_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PDS_TRGT_4_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_1_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_2_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_3_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_DX_WRONG_PORT_TRGT_4_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_UNEXPECTED_QUEUE_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_CAUSE_QCX_UNEXPECTED_QUEUE_1_INT_FIELD_SIZE			1

/* end of PDX_dbg_Interrupt_Cause*/


/* start of register PDX_dbg_Interrupt_Mask*/

#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QGRPMAP_DROPS_INTERRUPT_CAUSE_MASK_FIELD_OFFSET			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_WRONG_PORTMAP_ADDR_CP0_INTERRUPT_CAUSE_MASK_FIELD_OFFSET			2
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_WRONG_PDS_TRGT_CP0_INTERRUPT_CAUSE_MASK_FIELD_OFFSET			4
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_WRONG_PORT_CP0_INTERRUPT_CAUSE_MASK_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_0_FIELD_OFFSET			8
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_1_FIELD_OFFSET			9
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_2_FIELD_OFFSET			10
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_3_FIELD_OFFSET			11
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_4_FIELD_OFFSET			12
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_0_FIELD_OFFSET			16
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_1_FIELD_OFFSET			17
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_2_FIELD_OFFSET			18
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_3_FIELD_OFFSET			19
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_4_FIELD_OFFSET			20
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_0_FIELD_OFFSET			24
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_1_FIELD_OFFSET			25
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_2_FIELD_OFFSET			26
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_3_FIELD_OFFSET			27
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_4_FIELD_OFFSET			28
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_UNEXPECTED_QUEUE_CAUSE_MASK_0_FIELD_OFFSET			29
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_UNEXPECTED_QUEUE_CAUSE_MASK_1_FIELD_OFFSET			30


#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QGRPMAP_DROPS_INTERRUPT_CAUSE_MASK_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_WRONG_PORTMAP_ADDR_CP0_INTERRUPT_CAUSE_MASK_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_WRONG_PDS_TRGT_CP0_INTERRUPT_CAUSE_MASK_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_WRONG_PORT_CP0_INTERRUPT_CAUSE_MASK_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_0_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_1_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_2_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_3_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_INDEX_INTERRUPT_CAUSE_MASK_4_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_0_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_1_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_2_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_3_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PDS_INTERRUPT_CAUSE_MASK_4_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_0_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_1_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_2_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_3_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_DX_WRONG_TRGT_PORT_INTERRUPT_CAUSE_MASK_4_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_UNEXPECTED_QUEUE_CAUSE_MASK_0_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_DBG_INTERRUPT_MASK_QCX_UNEXPECTED_QUEUE_CAUSE_MASK_1_FIELD_SIZE			1

/* end of PDX_dbg_Interrupt_Mask*/


/* start of register Address_Violation*/

#define      TXQ_AAS_PDX_ADDRESS_VIOLATION_ADDRESS_VIOLATION_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_ADDRESS_VIOLATION_ADDRESS_VIOLATION_FIELD_SIZE         32

/* end of Address_Violation*/


/* start of register PDX_Interrupt_Summary_Cause*/

#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_INT_SUM_FIELD_OFFSET           0
#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_FUNC_INTSUM_FIELD_OFFSET           1
#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_DBG_INTSUM_FIELD_OFFSET            2


#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_INT_SUM_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_FUNC_INTSUM_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_DBG_INTSUM_FIELD_SIZE          1

/* end of PDX_Interrupt_Summary_Cause*/


/* start of register PDX_Interrupt_Summary_Mask*/

#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_FUNC_INTSUM_MASK_FIELD_OFFSET           1
#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_DBG_INTSUM_MASK_FIELD_OFFSET            2


#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_FUNC_INTSUM_MASK_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_DBG_INTSUM_MASK_FIELD_SIZE          1

/* end of PDX_Interrupt_Summary_Mask*/


/* start of register PDX_Functional_Interrupt_Cause*/

#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_FUNC_INTSUM_FIELD_OFFSET			0
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_OFFSET			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_BURST_FIFO_DROP_INT_FIELD_OFFSET			2
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS0_INT_FIELD_OFFSET			3
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS1_INT_FIELD_OFFSET			4
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS2_INT_FIELD_OFFSET			5
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS3_INT_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS4_INT_FIELD_OFFSET			7
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_SER_INT_FIELD_OFFSET			11


#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_FUNC_INTSUM_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_BURST_FIFO_DROP_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS0_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS1_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS2_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS3_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_DROP_PDS4_INT_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_SER_INT_FIELD_SIZE			1

/* end of PDX_Functional_Interrupt_Cause*/


/* start of register PDX_Functional_Interrupt_Mask*/

#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_ILLEGAL_ADDRESS_MASK_FIELD_OFFSET			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_BF_DROPS_INTERRUPT_CAUSE_MASK_FIELD_OFFSET			2
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_0_FIELD_OFFSET			3
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_1_FIELD_OFFSET			4
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_2_FIELD_OFFSET			5
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_3_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_4_FIELD_OFFSET			7
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_SER_INT_MASK_FIELD_OFFSET			11


#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_ILLEGAL_ADDRESS_MASK_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_BF_DROPS_INTERRUPT_CAUSE_MASK_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_0_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_1_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_2_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_3_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_DESC_DROP_INTERRUPT_CAUSE_MASK_4_FIELD_SIZE			1
#define      TXQ_AAS_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_SER_INT_MASK_FIELD_SIZE			1

/* end of PDX_Functional_Interrupt_Mask*/


/* start of register pfcc_burst_fifo_thr*/

#define      TXQ_AAS_PDX_PFCC_BURST_FIFO_THR_PFCC_BURST_FIFO_THR_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_PFCC_BURST_FIFO_THR_PFCC_BURST_FIFO_THR_FIELD_SIZE         10

/* end of pfcc_burst_fifo_thr*/


/* start of register global_burst_fifo_thr*/

#define      TXQ_AAS_PDX_GLOBAL_BURST_FIFO_THR_GLOBAL_BURST_FIFO_THR_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_GLOBAL_BURST_FIFO_THR_GLOBAL_BURST_FIFO_THR_FIELD_SIZE         10

/* end of global_burst_fifo_thr*/


/* start of register micro_Memory_Traffic_Counter*/

#define      TXQ_AAS_PDX_MICRO_MEMORY_TRAFFIC_COUNTER_MICRO_MEMORY_TRAFFIC_COUNTER_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_MICRO_MEMORY_TRAFFIC_COUNTER_MICRO_MEMORY_TRAFFIC_COUNTER_FIELD_SIZE           32

/* end of micro_Memory_Traffic_Counter*/


/* start of register Micro_memory_bank_fill_level*/

#define      TXQ_AAS_PDX_MICRO_MEMORY_BANK_FILL_LEVEL_MICRO_MEMORY_BANK_FILL_LEVEL_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_MICRO_MEMORY_BANK_FILL_LEVEL_MICRO_MEMORY_BANK_FILL_LEVEL_FIELD_SIZE           10

/* end of Micro_memory_bank_fill_level*/


/* start of register global_burst_fifo_available_entries*/

#define      TXQ_AAS_PDX_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_FIELD_SIZE         18

/* end of global_burst_fifo_available_entries*/


/* start of register max_bank_fill_levels*/

#define      TXQ_AAS_PDX_MAX_BANK_FILL_LEVELS_MAX_BANK_FILL_LEVELS_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_MAX_BANK_FILL_LEVELS_MAX_BANK_FILL_LEVELS_FIELD_SIZE           10

/* end of max_bank_fill_levels*/


/* start of register MIN_Global_Burst_Fifo_Available_Entries*/

#define      TXQ_AAS_PDX_MIN_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_MIN_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_MIN_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_MIN_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_FIELD_SIZE         18

/* end of MIN_Global_Burst_Fifo_Available_Entries*/


/* start of register DX_Wrong_Trg_Port_Map_Addr*/

#define      TXQ_AAS_PDX_DX_WRONG_TRG_PORT_MAP_ADDR_DX_WRONG_LOCAL_DEV_TRG_PHY_PORT_FIELD_OFFSET			0


#define      TXQ_AAS_PDX_DX_WRONG_TRG_PORT_MAP_ADDR_DX_WRONG_LOCAL_DEV_TRG_PHY_PORT_FIELD_SIZE			10

/* end of DX_Wrong_Qgrpmap_Addr*/


/* start of register DX_Wrong_PDS_Target*/

#define      TXQ_AAS_PDX_DX_WRONG_PDS_TARGET_DX_WRONG_PDS_TRGT_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_DX_WRONG_PDS_TARGET_DX_WRONG_PDS_TRGT_FIELD_SIZE           3

/* end of DX_Wrong_PDS_Target*/


/* start of register PDS_Drop_Counter*/

#define      TXQ_AAS_PDX_PDS_DROP_COUNTER_PDS_DESC_DROP_COUNT_FIELD_OFFSET          0


#define      TXQ_AAS_PDX_PDS_DROP_COUNTER_PDS_DESC_DROP_COUNT_FIELD_SIZE            32

/* end of PDS_Drop_Counter*/


/* start of register DX_Wrong_PORT_Target*/

#define      TXQ_AAS_PDX_DX_WRONG_PORT_TARGET_DX_WRONG_PORT_TRGT_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_DX_WRONG_PORT_TARGET_DX_WRONG_PORT_TRGT_FIELD_SIZE         6

/* end of DX_Wrong_PORT_Target*/


/* start of register rx_port*/

#define      TXQ_AAS_PDX_RX_PORT_RX_PORT_FIELD_OFFSET           0


#define      TXQ_AAS_PDX_RX_PORT_RX_PORT_FIELD_SIZE         6

/* end of rx_port*/



/* start of register epb_fifo_thr*/

#define      TXQ_AAS_PDX_EPB_FIFO_THR_EPB_FIFO_THR_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_EPB_FIFO_THR_EPB_FIFO_THR_FIELD_SIZE           4

/* end of epb_fifo_thr*/


/* start of register pds_msg_map_pds_id*/

#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_0_FIELD_OFFSET           0
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_1_FIELD_OFFSET           3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_2_FIELD_OFFSET           6
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_3_FIELD_OFFSET           9
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_4_FIELD_OFFSET           12
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_5_FIELD_OFFSET           15
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_6_FIELD_OFFSET           18
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_7_FIELD_OFFSET           21
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_8_FIELD_OFFSET           24
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_9_FIELD_OFFSET           27


#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_0_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_1_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_2_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_3_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_4_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_5_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_6_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_7_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_8_FIELD_SIZE         3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDS_ID_PDS_MSG_MAP_PDS_ID_9_FIELD_SIZE         3

/* end of pds_msg_map_pds_id*/


/* start of register pds_msg_map_pdx_id*/

#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_0_FIELD_OFFSET           0
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_1_FIELD_OFFSET           1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_2_FIELD_OFFSET           2
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_3_FIELD_OFFSET           3
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_4_FIELD_OFFSET           4
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_5_FIELD_OFFSET           5
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_6_FIELD_OFFSET           6
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_7_FIELD_OFFSET           7
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_8_FIELD_OFFSET           8
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_9_FIELD_OFFSET           9


#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_0_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_1_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_2_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_3_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_4_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_5_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_6_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_7_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_8_FIELD_SIZE         1
#define      TXQ_AAS_PDX_PDS_MSG_MAP_PDX_ID_PDS_MSG_MAP_PDX_ID_9_FIELD_SIZE         1

/* end of pds_msg_map_pdx_id*/


/* start of register Telemetry_Decay_Counter_Threshold*/

#define      TXQ_AAS_PDX_TELEMETRY_DECAY_COUNTER_THRESHOLD_DECAY_COUNTER_THRESHOLD_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_TELEMETRY_DECAY_COUNTER_THRESHOLD_DECAY_COUNTER_THRESHOLD_FIELD_SIZE           32

/* end of Telemetry_Decay_Counter_Threshold*/


/* start of register Renaming_Enable*/

#define      TXQ_AAS_PDX_RENAMING_ENABLE_QUEUE_RENAMING_EN_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_RENAMING_ENABLE_QUEUE_RENAMING_EN_FIELD_SIZE           1

/* end of Renaming_Enable*/


/* start of register CP_Renaming_Disable_Error_Queue*/

#define      TXQ_AAS_PDX_CP_RENAMING_DISABLE_ERROR_QUEUE_QUEUE_FIELD_OFFSET         0


#define      TXQ_AAS_PDX_CP_RENAMING_DISABLE_ERROR_QUEUE_QUEUE_FIELD_SIZE           15

/* end of CP_Renaming_Disable_Error_Queue*/


/* start of register qcx_dp_core_to_db_map*/

#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_0_FIELD_OFFSET			0
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_1_FIELD_OFFSET			2
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_2_FIELD_OFFSET			4
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_3_FIELD_OFFSET			6
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_4_FIELD_OFFSET			8


#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_0_FIELD_SIZE			2
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_1_FIELD_SIZE			2
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_2_FIELD_SIZE			2
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_3_FIELD_SIZE			2
#define      TXQ_AAS_PDX_QCX_DP_CORE_TO_DB_MAP_QCX_DP_CORE_TO_DB_PDS_4_FIELD_SIZE			2

/* end of qcx_dp_core_to_db_map*/


/* start of table entry dx_trg_port_map_0*/

#define      TXQ_AAS_PDX_DX_TRG_PORT_MAP_0_DP_CORE_LOCAL_TRG_PORT_FIELD_OFFSET			0


#define      TXQ_AAS_PDX_DX_TRG_PORT_MAP_0_DP_CORE_LOCAL_TRG_PORT_FIELD_SIZE			6

/* end of dx_trg_port_map_0*/


/* start of table entry qcx_trg_port_map_0*/

#define      TXQ_AAS_PDX_QCX_TRG_PORT_MAP_0_DP_CORE_LOCAL_TRG_PORT_FIELD_OFFSET			0


#define      TXQ_AAS_PDX_QCX_TRG_PORT_MAP_0_DP_CORE_LOCAL_TRG_PORT_FIELD_SIZE			6

/* end of qcx_trg_port_map_0*/


#endif
